### ISSUE TITLE
Disable Squeezer when WiFi signal is lost

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#103]
```
Hi,

currently Squeezer stays active in the notification bar, even if WiFi signal (and therefore
server connection) is lost.
In this case Squeezer should stop trying to connect to the server and disable the notification
bar entry.
```

Original issue reported on code.google.com by `thenktor` on 2014-09-03 07:38:47

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue. 

Thank you!
