### ISSUE TITLE
Now Playing does not update on player switch

### ISSUE THREAD

**Issue by Mark0ne** [nikclayton/android-squeezer#121]
Issue:
When switching between players, now playing information does not update. Seconds elapsed counter does switch.

Replicate:
1)On player 1, play any song or internet radio station.
2)Use the top left drop-drown menu to select player 2
3)Play any different song or internet radio station - No sync specified, two zones are separate.
4)Switch Back to player 1 using drop-down menu
5)Note that bottom-bar remains as the song for player 2.
6)Click bottom bar. Now playing details are for player 2 although elapsed time counter is for player 1.

My Setup:
Squeezer 1.3.0
Android 5.0 on LG G3
Two Squeezeplug V2.12 Raspberry PIs, Server reports as Squeezelite 1.8
Second Player has recently been added - suspect this is not significant but let me know if you can't replicate.
Server is Zyxel NSA320, Squeezecenter version reported as 'Logitech Media Server Version: 7.7.1 - r33735'

Small issue in an excellent app. I really appreciate all the hard work - thank you.

**Comment by nikclayton** [comment]
Thanks for bug report. I've just fixed this, and the fix will be in the 1.3.1 release.

**Comment by nikclayton** [comment]
I've just published the 1.3.1-beta-1 release, which includes the fix for this.
