### ISSUE TITLE
Include Album Artists

### ISSUE THREAD

**Issue by jvandenbroek** [nikclayton/android-squeezer#122]
I've just updated LMS to 7.9 and saw it has a (nice) distinguishing between All and Album Artists in it's web interface. However Squeezer only shows Artists which will show all artists in the library. Would be neat to have both selections available.

**Comment by nikclayton** [comment]
I haven't got 7.9 installed yet. What's the difference between the two options?

**Comment by jvandenbroek** [comment]
All Artists will show artists from all songs in your library, while Album Artists is like the old behavior and only showing artists from complete albums. Now Squeezer just shows All Artists, but I'd like to have both of them.

**Comment by Sirfon** [comment]
It'd be great to have Album Artist available - I have quite a lot of albums where the main artist is e.g. Artist A but individual tracks might have Artist as Artist A feat. Artist B - browsing Album Artist would only show Artist A whereas currently you end up trawling through loads of Artist A feat Artist B each with only one track.

Thanks for Squeezer, it's great!

**Comment by gs11** [comment]
Seems like there's no command to retrieve this through CLI. The official app fetches it through json-rpc.

**Comment by kaaholst** [comment]
Fixed in 2.0.0
