### ISSUE TITLE
Allow setting interface language

### ISSUE THREAD

**Issue by jvandenbroek** [nikclayton/android-squeezer#123]
Now Squeezer adapts the system language, however I'd like to select another language manually (my system is Dutch but I prefer English for apps).

**Comment by nikclayton** [comment]
Note to self: if considering this, look in to https://github.com/delight-im/Android-Languages

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
