### ISSUE TITLE
squeezer not working after reinstall LMS

### ISSUE THREAD

**Issue by chicamaxi** [nikclayton/android-squeezer#124]
I was using squeezer untill last week, it's not working anymore since I reinstalled Logitech Media Server 7.7.6 on my Ubuntu 12.04 server. The scan finds my server on port 9090, but "connect" fails...I tested this on 3 different android devices already. The official Logitech 2012 app is working though...can I check any log files in the app?

**Comment by nikclayton** [comment]
On 5 June 2015 at 07:22, chicamaxi <notifications@github.com> wrote:

> I was using squeezer untill last week, it's not working anymore since I
> reinstalled Logitech Media Server 7.7.6 on my Ubuntu 12.04 server. The scan
> finds my server on port 9090, but "connect" fails...I tested this on 3
> different android devices already. The official Logitech 2012 app is
> working though...can I check any log files in the app?
>
Is there any chance that when you upgraded the server you turned off CLI
access to it in the settings?

N
-- 
http://try-dot-ch.blogspot.com/

**Comment by chicamaxi** [comment]
Seems like the CLI is ok on my Ubuntu box :
telnet 192.168.0.4 9090
Trying 192.168.0.4...
Connected to 192.168.0.4.
Escape character is '^]'.
Any clue?

**Comment by chicamaxi** [comment]
Tried on 2 more Android devices without success...strange because the
original Logitech app and orange squeeze do work?!

In my LMS settings I see:

Logitech Media Server Version: 7.7.6 - 1432793151 @ Tue Jun 2 02:03:57 UTC
2015
Hostname: NUCXBMC
Server IP Address: 192.168.0.4
Server HTTP Port Number: 9000
Operating system: Debian - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.14.2 - x86_64-linux-gnu-thread-multi
Database Version: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Total Players Recognized: 5


Op vrijdag 5 juni 2015 heeft Koen Van lent <vanlent.koen@gmail.com> het
volgende geschreven:

> Seems like the CLI is ok on my Ubuntu box :
> telnet 192.168.0.4 9090
> Trying 192.168.0.4...
> Connected to 192.168.0.4.
> Escape character is '^]'.
> Any clue?
>
>
> On Fri, Jun 5, 2015 at 1:47 PM, Nik Clayton <notifications@github.com

**Comment by nikclayton** [comment]
On 6 June 2015 at 09:31, chicamaxi <notifications@github.com> wrote:

> Tried on 2 more Android devices without success...strange because the
> original Logitech app and orange squeeze do work?!
>

When the connection fails it should show a toast message. What's the text
of that message?

Also, can you browse the web UI of the server from your phone?  I.e., can
you open http://192.168.0.4:9000 in the browser?

N
-- 
http://try-dot-ch.blogspot.com/

**Comment by chicamaxi** [comment]
Works perfect now... a hard reboot of my linux box did the job.
Thanks anyways!

**Comment by nikclayton** [comment]
Hmm, very odd. Glad it's resolved now though.
