### ISSUE TITLE
Notification not updating

### ISSUE THREAD

**Issue by noaddress** [nikclayton/android-squeezer#125]
Hi there
As mentioned on G+, here are more infos about my problem. I also discovered that when I deactivate notification on connection in the settings that the notification disappears as soon as I change tracks on the squeezebox (next song in playlist for example) It only started happening with the latest update of squeezer. I've already reset the app data and the problem is still here. Updating CyanogenMod didn't help either.

Squeezer version 1.3.1-beta-2
Oneplus One
CyanogenMod Nightly 20150616
Android 5.1.1
Atm it's always the case, it doesn't matter if I'm playing music via spotify or directly from my local NAS running LMS 7.7.1

https://plus.google.com/101244391291592554400/posts/AdtKYUz1NNY

**Comment by nikclayton** [comment]
I think I've got a fix for this. If I sent you a .apk file would you be able to install it on your device to check?

**Comment by noaddress** [comment]
yeah, of course. I'd be more than happy to help and get this resolved :)

**Comment by nikclayton** [comment]
Cheers. If you go to https://gist.github.com/nikclayton/5d54f1006f5ad1037949 you should see a link to another Squeezer beta apk. You'll need to uninstall the version you have installed right now, and then install this one using ADB over a USB connection.

**Comment by noaddress** [comment]
Well, I'm sorry but nothing changed. Sure it was the right apk? has still the same version 1.3.1-beta-2

**Comment by nikclayton** [comment]
Yeah, I didn't bump the version number for this test, it's just got the diff at https://gist.githubusercontent.com/nikclayton/5d54f1006f5ad1037949/raw/gistfile1.txt in it.

Ah. Just looked at that again, off by one error. I've just updated the apk in the gist, can you try again (make sure the "revisions" badge on the right hand side of the Gist page says "3" to make sure you've got the right one)?

And if that doesn't work, are you able to get a tcpdump or similar of the traffic between Squeezer and the server?

If you can, here's an example of what you should see going from the server to Squeezer in the seconds before one song finishes and another one starts.

The first four lines are status updates from the server as the player moves through the last four seconds of the song. Obviously, your values will be different depending on whatever track you're playing.

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 showBriefly:Now%20Playing%20(16%20of%2077)%20%2CMama%20Kin power:1 signalstrength:0 mode:play time:217.887970245361 rate:1 duration:223.947 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:15 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:15 id:37 title:Mama%20Kin artist:Aerosmith compilation:0 duration:223.947 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:12 remote:0 year:1975 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F12%2520-%2520Aerosmith%2520-%2520Mama%2520Kin.mp3

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 showBriefly:Now%20Playing%20(16%20of%2077)%20%2CMama%20Kin power:1 signalstrength:0 mode:play time:218.898251163483 rate:1 duration:223.947 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:15 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:15 id:37 title:Mama%20Kin artist:Aerosmith compilation:0 duration:223.947 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:12 remote:0 year:1975 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F12%2520-%2520Aerosmith%2520-%2520Mama%2520Kin.mp3

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 showBriefly:Now%20Playing%20(16%20of%2077)%20%2CMama%20Kin power:1 signalstrength:0 mode:play time:219.910422142029 rate:1 duration:223.947 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:15 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:15 id:37 title:Mama%20Kin artist:Aerosmith compilation:0 duration:223.947 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:12 remote:0 year:1975 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F12%2520-%2520Aerosmith%2520-%2520Mama%2520Kin.mp3

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 power:1 signalstrength:0 mode:play time:220.898862190247 rate:1 duration:223.947 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:15 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:15 id:37 title:Mama%20Kin artist:Aerosmith compilation:0 duration:223.947 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:12 remote:0 year:1975 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F12%2520-%2520Aerosmith%2520-%2520Mama%2520Kin.mp3

Then you should see this a "playlist newsong" entry -- this is the indicator that a new song has started.

00:00:00:00:00:01 playlist newsong S.O.S.%20(Too%20Bad) 16

Then the server starts sending data about the new song as it plays  -- these four lines represent the first four seconds.

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 power:1 signalstrength:0 mode:play time:0 rate:1 duration:170.84 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:16 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:16 id:38 title:S.O.S.%20(Too%20Bad) artist:Aerosmith compilation:0 duration:170.84 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:13 remote:0 year:1978 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F13%2520-%2520Aerosmith%2520-%2520S.O.S.%2520(Too%2520Bad).mp3

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 power:1 signalstrength:0 mode:play time:1.28118119239807 rate:1 duration:170.84 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:16 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:16 id:38 title:S.O.S.%20(Too%20Bad) artist:Aerosmith compilation:0 duration:170.84 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:13 remote:0 year:1978 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F13%2520-%2520Aerosmith%2520-%2520S.O.S.%2520(Too%2520Bad).mp3

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 power:1 signalstrength:0 mode:play time:2.29251323699951 rate:1 duration:170.84 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:16 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:16 id:38 title:S.O.S.%20(Too%20Bad) artist:Aerosmith compilation:0 duration:170.84 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:13 remote:0 year:1978 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F13%2520-%2520Aerosmith%2520-%2520S.O.S.%2520(Too%2520Bad).mp3

00:00:00:00:00:01 status - 1 subscribe:1 tags:aCdejJKlstxyu player_name:Squeezeslave player_connected:1 player_ip:127.0.0.1:42072 power:1 signalstrength:0 mode:play time:3.28005826187134 rate:1 duration:170.84 can_seek:1 mixer%20volume:69 playlist%20repeat:0 playlist%20shuffle:0 playlist%20mode:off seq_no:0 playlist_cur_index:16 playlist_timestamp:1434746107.88223 playlist_tracks:77 playlist%20index:16 id:38 title:S.O.S.%20(Too%20Bad) artist:Aerosmith compilation:0 duration:170.84 album_id:14 coverart:1 artwork_track_id:865c9580 album:Live%20Bootleg artist_id:12 tracknum:13 remote:0 year:1978 url:file:%2F%2F%2Fhome%2Fnik%2FMusic%2FAerosmith%2FLive%2520Bootleg%2F13%2520-%2520Aerosmith%2520-%2520S.O.S.%2520(Too%2520Bad).mp3

**Comment by noaddress** [comment]
Now everything works fine again, thank you so much for resolving this!
Guess there's no need for the tcpdump anymore.

Should another problem arise in the future and you need someone to test it, feel free to ask (G+)
Thank you and have a nice day

**Comment by nikclayton** [comment]
Thanks. One thing -- you might need to uninstall the .apk you got from here, and re-download Squeezer from Google Play. I'm not 100% certain, but by installing from the downloaded .apk that might have broken the link to Google Play, and you won't get updates automatically unless you delete it and re-install.

**Comment by noaddress** [comment]
Ok, will do that. Thanks.
