### ISSUE TITLE
Notification closes and reopens when changing track

### ISSUE THREAD

**Issue by michiil** [nikclayton/android-squeezer#130]
As said in the title the player notification closes when changing the track. It reopens as soon as the new track is playing .

**Comment by nikclayton** [comment]
What you're seeing at the moment is that when the server goes from one track to the next it sends Squeezer a "the song has paused" message (which makes the notification go away). Then it starts playing the next song, and sends a "a song has started" message, and the notification comes back.

I've got a fix for this which will probably be in the next release, but until then, a quick fix for this (if you don't mind the notification being there while Squeezer is connected) is to go in to Squeezer's settings and enable the "Notify of connection" option.

**Comment by nikclayton** [comment]
This'll be out in the release after next (1.4.0 is coming in a day or two, so it'll be in 1.4.1).
