### ISSUE TITLE
Feature Request: Create folder structure based on tags when downloading

### ISSUE THREAD

**Issue by bthoem** [nikclayton/android-squeezer#132]
Hi - would like to propose an enhancement to the Download feature, so that folders are created from the meta data in the downloaded files, similar to how it's implemented in Squeeze Commander.
- Download storage (SDcard or Internal)
- Download Base Path (e.g. /Music)
- Path Structure:
- AlbumArtist/Album/Track (default)
- Artist/Album/Track
- Artist/Track
- Album/Track
- Track
- Filename Structure:
- Original Filename (default)
- Num. Track - Artist - Album
- Num. Track - Artist
- Num. Track
- Track - Artist - Album
- Track - Artist
- Track
- Transcoding (Enable Transcoding, Target Format, Source Formats, Bitrate, Quality)

Let me know if you need more details - the most important feature for me is the creation of folders.

Bjørn Tore Hoem

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by kaaholst** [comment]
This is implemented in the most recent version of Squeezer, except for SDCard, which isn't really supported on Android.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
