### ISSUE TITLE
Filenames in playlist

### ISSUE THREAD

**Issue by ghost** [nikclayton/android-squeezer#133]
![2015-07-11 22 16 46](https://cloud.githubusercontent.com/assets/6025835/8635238/62b00acc-281b-11e5-91b9-d93021e8b6fa.jpg)
When possible, i would like to see the filenames in the playlist to avoid the shown in the picture,
also in the android menu (the one you can slice down)

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
