### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by trouty00** [nikclayton/android-squeezer#136]
Im trying to control the app with ADB over the network and whilst I can load the application fine with adb shell am start -a android.intent.action.VIEW -n uk.org.ngo.squeezer/uk.org.ngo.squeezer.HomeActivity I would love a way to launch the now playing screen in a similar fashion. In pretty new at this game but have tried a few things after looking at the manifest but cant quite figure it out.

Ta
Stu

**Comment by kaaholst** [comment]
Just substitute HomeActivity with NowplayingActivity:
adb shell am start -a android.intent.action.VIEW -n uk.org.ngo.squeezer/uk.org.ngo.squeezer.NowPlayingActivity

**Comment by trouty00** [comment]
I thought this as well but I get a permission denial when trying to do
this, tried two different ADB clients and same results.

On Sun, Aug 2, 2015 at 9:38 AM, Kurt Aaholst <notifications@github.com>
wrote:

> Just substitute HomeActivity with NowplayingActivity:
> adb shell am start -a android.intent.action.VIEW -n
> uk.org.ngo.squeezer/uk.org.ngo.squeezer.NowPlayingActivity
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nikclayton/android-squeezer/issues/136#issuecomment-126999362>
> .
>



-- 
skype :stu.trout
MSN  : trouty00@hotmail.com

**Comment by kaaholst** [comment]
Hmm...
Works for me, don't know why you get permission denied. Not sure it's an ADB issue though.

**Comment by trouty00** [comment]
Interesting, will do more testing with usb connected( currently doing over network). Have no issue with the homeactivity though

**Comment by kaaholst** [comment]
Just did a few more tests.

To be able to start an activity from other applications (such as ADB) it needs to exported. HomeActivity is implicitly exported, but NowPlayingActivity is not. This is consistent with the documentation of the exported flag, which is pasted below, and my test results. I tested on a 4.4 device which denies start of NowPlayingActivity, on both network and USB, and a 4.0.3 emulator. The first time I tried, was an API 22 (Android 5.1) emulator, which for some reason allowed the launch.

Exported flag documentation:
Flag indicating whether the given application component is available to other applications. If false, it can only be accessed by applications with its same user id (which usually means only by code in its own package). If true, it can be invoked by external entities, though which ones can do so may be controlled through permissions. The default value is false for activity, receiver, and service components that do not specify any intent filters; it is true for activity, receiver, and service components that do have intent filters (implying they expect to be invoked by others who do not know their particular component name) and for all content providers.

**Comment by trouty00** [comment]
sorry, I have been away, moved house and only just got back to looking at this, even more so because i know have an android TV so this is even more frustrating. so is there anyway I can make this work at all or does it need to be added in as a change to the code by the developer?

do you think this is something which could be done?

**Comment by kaaholst** [comment]
Yes I can export the NowPlayingActivity for you, so it will be available in the next version.

I am reluctant to simply export all activites, as most of them takes some parameters which are calculated internally by Squeezer when it starts them. However NowPlayingActivity seems like a perfectly fine use case to be started externally. The same goes for CurrentPlaylistActivity, so I will export this as well. 

The SearchActivity can be started externally giving a SEARCH intent. i am not really sure how this works though.

**Comment by trouty00** [comment]
Awesome! Thanks and look forward to it!!

**Comment by kaaholst** [comment]
I have committed a patch which exports the Now Playing and Current Playlist activities. This will be available in a later version.

Mini HOWTO:

* Show the main menu:  
  adb shell am start -a android.intent.action.VIEW -n uk.org.ngo.squeezer/uk.org.ngo.squeezer.HomeActivity
* Show the Now playing screen:  
  adb shell am start -a android.intent.action.VIEW -n uk.org.ngo.squeezer/uk.org.ngo.squeezer.NowPlayingActivity
* Show the current playlist:  
  adb shell am start -a android.intent.action.VIEW -n uk.org.ngo.squeezer/uk.org.ngo.squeezer.itemlist.CurrentPlaylistActivity
* Search for artist/album/song/genre:  
  adb shell am start -a android.intent.action.SEARCH -n uk.org.ngo.squeezer/uk.org.ngo.squeezer.SearchActivity -e query "Trust"

**Comment by trouty00** [comment]
Hi Kurt,
 just came back to this after a while and just wondering if you have any
plans to push out a new version anytime soon?

Stu

On Mon, Sep 21, 2015 at 7:23 PM, Kurt Aaholst <notifications@github.com>
wrote:

> I have committed a patch which exports the Now Playing and Current
> Playlist activities. This will be available in a later version.
>
> Mini HOWTO:
>
>    - Show the main menu:
>    adb shell am start -a android.intent.action.VIEW -n
>    uk.org.ngo.squeezer/uk.org.ngo.squeezer.HomeActivity
>    - Show the Now playing screen:
>    adb shell am start -a android.intent.action.VIEW -n
>    uk.org.ngo.squeezer/uk.org.ngo.squeezer.NowPlayingActivity
>    - Show the current playlist:
>    adb shell am start -a android.intent.action.VIEW -n
>    uk.org.ngo.squeezer/uk.org.ngo.squeezer.itemlist.CurrentPlaylistActivity
>    - Search for artist/album/song/genre:
>    adb shell am start -a android.intent.action.SEARCH -n
>    uk.org.ngo.squeezer/uk.org.ngo.squeezer.SearchActivity -e query "Trust"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nikclayton/android-squeezer/issues/136#issuecomment-142067181>
> .
>



-- 
skype :stu.trout
MSN  : trouty00@hotmail.com

**Comment by kaaholst** [comment]
Hopefully we have a new version out soon, with the requested functionality.

**Comment by trouty00** [comment]
hi,
  has a new version been released at all yet to fix this?

Regards
Stu

On Wed, Apr 27, 2016 at 11:06 PM, Kurt Aaholst <notifications@github.com>
wrote:

> Hopefully we have a new version out soon, with the requested functionality.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nikclayton/android-squeezer/issues/136#issuecomment-215245381>
>



-- 
skype :stu.trout
MSN  : trouty00@hotmail.com

**Comment by kaaholst** [comment]
Yes it is available in version 1.4.1 which is available on [Google Play](https://play.google.com/store/apps/details?id=uk.org.ngo.squeezer)
