### ISSUE TITLE
Can't search in Deezer

### ISSUE THREAD

**Issue by alvaro-oliver** [nikclayton/android-squeezer#138]
What steps will reproduce the problem?
1. Go to menu entry "My Apps"
2. Select app "Deezer"
3. Select the "Search music" submenu
4. (Optional: type "beatles" in the upper Squeezer search tool)
5. Select any submenu: "Search For Artist", "...Albums" or "...Tracks"

![screenshot_2015-08-05-07-22-24](https://cloud.githubusercontent.com/assets/13628819/9120054/8d48f9da-3c50-11e5-89e9-37cf1cc38bc1.png)

What is the expected output? What do you see instead?

Squeezer should return a results list based on the "beatles" string. Instead, "Search results for {QUERY}" is returned.

It is clear to me that Squeezer is not passing any query string to Deezer search engine.

![screenshot_2015-08-05-07-22-41](https://cloud.githubusercontent.com/assets/13628819/9120076/acf02394-3c50-11e5-9879-555ab36bd90f.png)

What version of the product are you using? On what operating system?
App: Squeezer 1.4.0
Phone: Samsung Galaxy S3
OS: Android KitKat (cyanogenmod firmware)

Please provide any additional information below.

Deezer search is very good implemented on Daphile player web UI.
![screenshot_2015-08-05-07-24-10](https://cloud.githubusercontent.com/assets/13628819/9120100/c57d4cc0-3c50-11e5-94b5-9f755d6b0e8e.png)

![screenshot_2015-08-05-07-24-21](https://cloud.githubusercontent.com/assets/13628819/9120113/d50d33c6-3c50-11e5-9d4f-f8ed45fa0598.png)

**Comment by chau-intl** [comment]
I can confirm the issue but I'm also on the same Squeezer version. 

One thing I don't understand though is where I have to input my search string? If II type a search string in the squeezer search field, the search is performed in my local music repository and not in Deeper.

**Comment by kaaholst** [comment]
https://github.com/nikclayton/android-squeezer/wiki/Apps-support-in-Squeezer

**Comment by Flautz** [comment]
I added Pull request #184 which fixes that topic.

**Comment by assurancetourix** [comment]
I have squeezer 1.4.1 on android 5.1.1 (samsung), and still get the issue.

**Comment by kaaholst** [comment]
Search will be available for Deezer in the next release of Squeezer, which is currently being prepared and tested.
It is due in a few weeks.

**Comment by nikclayton** [comment]
1.5.0 is released, which should fix this, so closing this issue. If you still see a problem, please re-open it.
