### ISSUE TITLE
Internet radio search doesn't work? 

### ISSUE THREAD

**Issue by chau-intl** [nikclayton/android-squeezer#141]
I prefer to search using keywords when trying to locate an internet radio station that suits my listening preferences. 

When clicking on Internet radio and select search, I'm brought to a new empty screen. The default search icon is still visible in top actionbar but as far as I can tell, it just searches my local music repository. 

I have previously used the original logitech app for this single purpose of finding and adding a radio station to my playlist, but since I have upgraded my devices to android 5.1.x and the app seems to have been abandoned, I no longer can use this approach. 

Is the search feature just not completely finished yet or should I be able to search for internet radio stations?

**Comment by kaaholst** [comment]
A fix for this is in development, will be out in new version soon.

**Comment by chau-intl** [comment]
Great, I'm looking forward to the beta :-)

**Comment by kaaholst** [comment]
This is available now, so closing this
