### ISSUE TITLE
Feature request: Grid view for devices with large screens 

### ISSUE THREAD

**Issue by chau-intl** [nikclayton/android-squeezer#142]
I can see that this request has been mentioned in a previous issue but is ignored until more users request it. So I would like to request an option to also show lists in a grid view :-) 

Even being able to browse a list by having ex. 3 items on a row (like a shelf, I think this was used by iTunes way back)  has been requested by a couple of my friends trying out this app. The reason is that some people seem to navigate their music library visually and thus prefer larger artworks instead of many results visible at the same time.

**Comment by kaaholst** [comment]
Currently the Albums and Songs lists have a grid view.

To enable this select View from the options menu on the relevant list and then select Large Covers, as shown on the screen-shots below.

If you meant something else/more, please report back.

![album-list](https://cloud.githubusercontent.com/assets/428304/9262308/3a981ab2-4214-11e5-9bab-e371d7d081b8.png)

![album-menu](https://cloud.githubusercontent.com/assets/428304/9262313/451388fa-4214-11e5-9e45-6075c5c9ee58.png)

![album-view-dialog](https://cloud.githubusercontent.com/assets/428304/9262316/4bcd5446-4214-11e5-8c48-32fcafeade35.png)

![album-grid](https://cloud.githubusercontent.com/assets/428304/9262320/50dacf40-4214-11e5-835c-6aa7651b862b.png)

**Comment by chau-intl** [comment]
Hey Kurt

It's exactly what I'm looking for. I just don't use either of the album or song entrance to my music collection. I normally go through the search or the music folder. Would it be possible to extend the layouts of those to also support the grid view? 

Would it be possible to further increase the cell sizes? Maybe an option to set the number og rows and columns instead? That would allow much more flexibility. 

I'm just dreaming and thanks for the showcase :-)

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
