### ISSUE TITLE
push down on internet radio does not play

### ISSUE THREAD

**Issue by Kclemen** [nikclayton/android-squeezer#144]
intuitive push on the name of an internet radio does not play the radio station. Instead you have to press on the right side to get a list and select play. The symbol for the drop down list is very near to the slidebar., resulting most of the time in a shift of the list. Very annoying.

Would it be possible to just play the internet radio with a single press on the name?

**Comment by kaaholst** [comment]
The request is noted.

One problem is that playing the radio station when the name is pressed, will loose the current playlist, which would be annoying to some.

One solution could be to have this behaviour user selectable.

**Comment by knoer** [comment]
I too have unintentionally scrolled the list of radio stations, when trying to open the pop-up menu.

Could this be solved by adding an additional "direct play" button to the left of the current pop-up/menu button?
This way, it would still require the user to press it intentionally, but should prevent unintentional activations when scrolling a list of radio stations?

Running Squeezer 1.4 on a Nexus 5.

**Comment by kaaholst** [comment]
Action when pressing a radio station is now controlled by the server (can be customized via the "Defeat destructive touch-to-play" player setting, which is available from the players screen).
