### ISSUE TITLE
YouTube app doesn't let you search

### ISSUE THREAD

**Issue by stephen-d-hill** [nikclayton/android-squeezer#145]
YouTube app doesn't let you search when search selected. Seems to be auto searching, but not sure what. Logitech Squeezebox app works fine, but unfortunately doesn't work on lollipop.

**Comment by kaaholst** [comment]
https://github.com/nikclayton/android-squeezer/wiki/Apps-support-in-Squeezer

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by nikclayton** [comment]
1.5.0 is released, which should fix this, so closing this issue. If you still see a problem, please re-open it.
