### ISSUE TITLE
Squeezer on amazon fire TV

### ISSUE THREAD

**Issue by castalla** [nikclayton/android-squeezer#146]
Works but with a few quirks ...
1. The focus does not fix on the first item in lists - requires an up button push on remote
2. In many lists the cursor won't move off the first item

**Comment by thenktor** [comment]
Same issues here. And furthermore I could not find a way to show the "now playing" screen.

**Comment by Stevelande** [comment]
Same here. I could not find a way to show the "now playing" screen

**Comment by kaaholst** [comment]
This is will be fixed when #119 is fixed, so closing this.
