### ISSUE TITLE
Feature Request: Local player/streaming

### ISSUE THREAD

**Issue by jnimble** [nikclayton/android-squeezer#147]
Since we can download music to phones and tablets, it would be nice if we could also play locally. That way we could preview the songs before downloading. I

I know you could just play it on one of the defined players, but by allowing playback locally you would have the ability to listen even if your not close to them.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
