### ISSUE TITLE
Can't search with Qobuz and Deezer!

### ISSUE THREAD

**Issue by anatolli** [nikclayton/android-squeezer#148]
Hello! 
I have found your app and it is great but i have an issue.
OS: Lollipop latest.
Unfortunatley it isn't possible to search in Qobuz nor in Deezer.
Maybee it can be fixed in the next release.

thanks a lot
anatolli

**Comment by kaaholst** [comment]
https://github.com/nikclayton/android-squeezer/wiki/Apps-support-in-Squeezer

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by ankumm** [comment]
I had the same problem. And its solved yet. 
Wonderful! Thank you very much!

**Comment by nikclayton** [comment]
1.5.0 is released, which should fix this, so closing this issue. If you still see a problem, please re-open it.
