### ISSUE TITLE
Long "Loading..." times when browsing by directory

### ISSUE THREAD

**Issue by mschwegel** [nikclayton/android-squeezer#149]
Overall this is an incredible app and I'm very glad it's there since the old official app no longer works.  I have a largish music collection, between 700 and 800 directories in my root music/ directory.  I prefer to browse by directory so that my sorting and naming is consistent (some remaining inconsistent tags mess with the structure when browsing by artists or albums).  However, I notice that while Squeezer seems to load the correct number of entries quickly giving a properly sized list right away, each one sits in a "Loading..." stage for a long time.  I'm curious what all it's doing in those loops and if perhaps some of it could be removed or delayed until at least the names themselves are loaded and displayed.  I see that the same sort of thing is happening when browsing artists, but when scrolling to a random area in the list the "Loading..." at least finishes quickly.  If I scroll to the middle of the directory view it can take some seconds, even half a minute, before I even know what I'm looking at.

**Comment by matt-matt2** [comment]
I've seen this when viewing folders over DLNA from LMS too, so I suspect this is an LMS issue.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
