### ISSUE TITLE
Rotation Issues

### ISSUE THREAD

**Issue by EliteSpartan** [nikclayton/android-squeezer#150]
Not sure if you might be able to help, but i've forked the code and for some reason, when i'm on the player in fullscreen, and then i rotate, it goes back to the mini player, but in full screen. do you know why this would be happening? 

Portrait when mini player is clicked.
![screenshot_2015-12-17-23-04-41](https://cloud.githubusercontent.com/assets/6450057/11869873/e7a2d09c-a512-11e5-9eb1-29b5d8460b6e.png)

Landscape after rotating from portrait.
![screenshot_2015-12-17-23-04-48](https://cloud.githubusercontent.com/assets/6450057/11869874/e7a3c68c-a512-11e5-870e-6dda2918386e.png)

**Comment by EliteSpartan** [comment]
I've narrowed down the issue to the two dependencies in the 'build.gradle' file:

    compile 'com.android.support:support-v4:21.0.0'
    compile 'com.android.support:appcompat-v7:21.0.0'

When i update these to the latest version, it prevents the method "onInflate" (in NowPlayingFragment.java) from running properly as it is now depricated from the support libraries.
Do you know how i would get the heights working properly again without using the "onInflate" method?

**Comment by EliteSpartan** [comment]
Fixed the issue with replacing the if statements in the 'OnCreateView' method. change:

    if (mFullHeightLayout) 

to

    if (mActivity instanceof NowPlayingActivity)

This will allow support for the new support libraries and shortens the code by a few lines.

**Comment by kaaholst** [comment]
Hi,

Thanks for investigating this.

You are welcome to create a pull request for this, so credit can go where it belongs :-)

I suggest you create a feature branch for this, and make the pull request from that. There seems to be other issues when updating the support libraries. That way, we can pull in the changes when we are ready.
