### ISSUE TITLE
Search function is broken in Spotify

### ISSUE THREAD

**Issue by tbrandysky** [nikclayton/android-squeezer#151]
Once Spotify plugin is installed on LMS 'Spotify' item appears under 'Internet Radio' entry. 
When I click to 'search' under Spotify I get "Spotify Error - bad search params' error.
The same thing works great with 'Squeezebox ctrl' app.

**Comment by kaaholst** [comment]
https://github.com/nikclayton/android-squeezer/wiki/Apps-support-in-Squeezer

**Comment by Flautz** [comment]
I added Pull request #184 which fixes that topic.

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by nikclayton** [comment]
1.5.0 is released, which should fix this, so closing this issue. If you still see a problem, please re-open it.
