### ISSUE TITLE
Feature Request - Samsung Gear

### ISSUE THREAD

**Issue by nobylspoon** [nikclayton/android-squeezer#153]
Yeah, I know its a niche market of an even smaller niche market but any chance of supporting a Samsung Gear app? Im sure the platform is quite different from the currently supported Android Wear but I figured I'd ask.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
