### ISSUE TITLE
Disconnect after playing song

### ISSUE THREAD

**Issue by 42kohd** [nikclayton/android-squeezer#154]
First off, thanks for an awesome app. I have used it for months, but recently it kicks me off the server as soon as I play anything and I cannot reconnect (I can connect when nothing is playing). It tries connecting 4-5 times super fast then kicks me back to rescan screen.

I see nothing in logitech server logs.

I am running Logitech Media Server Version: 7.9.0 - 1436071638

**Comment by kaaholst** [comment]
This sounds like a server or or a network issue. Personally I have no experience with server version 7.9, but I have no reason to suspect problems with that version.

I suggest that you check that the port settings matches in Squeezer and the server. In squeezer it is the part after the colon (":") on the rescan screen, and on the server it is found via settings/advanced/command line interface. Note that the port on the web interface (settings/advanced/network) can not be used. 

Also check that the security settings in the server matches (username and password), and allows Squeezer to connect.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue. 

Thank you!
