### ISSUE TITLE
Feature Request - Lyrics

### ISSUE THREAD

**Issue by dasquiddi** [nikclayton/android-squeezer#155]
Hi i would like to see the included lyrics in my songfiles in the app. Hopefully that is not connected with a lot of additional work =)

**Comment by diegomejia818** [comment]
Any updates on this feature?

**Comment by nilskp** [comment]
Just saw the latest version have this:

> Show lyrics if provided by the server.

**Comment by kaaholst** [comment]
Fixed in 1.5.3
