### ISSUE TITLE
gradle build errors

### ISSUE THREAD

**Issue by fhaertig** [nikclayton/android-squeezer#159]
Guys I really appreciate this project and wanted to contribute to it. But I spent now at least 2 days trying to build and debug it with Android Studio and failed miserably. I'm not a gradle pro, but it seems you're missing some dependencies or at least the setup is incomplete with libs:eventbus:EventBus. I tried to clone it into the libs folder and add it as a module in the IDE, but this doesn't solve the problem. 
Would be nice if you could give some more hints on this!

**Comment by kaaholst** [comment]
I have the same problem. I don't know the cause but as far as I recall, it started when we pulled in a fork of EventBus to handle an [issue in EventBus](https://github.com/greenrobot/EventBus/issues/149#issuecomment-76316437)
The problem you describe It causes an error message when Android Studio is started, and some compile errors in some classes when they are opened in Android studio. The Squeezer app however compiles and runs fine when building with gradle (even when invoked from inside Android Studio), so for now I am able to work with code.

I'll let you know when/if I find out more about this issue.

**Comment by kaaholst** [comment]
I have experimented some more with this issue.

I upgraded to EventBus 2.4.1, which fixes the issue we had with the module, and removed it as a sub project.

If you can live with problems described in my previous message, you can wait for his to reach the develop branch. Alternative you can fork my [git hub repository](https://github.com/kaaholst/android-squeezer), and work from the develop branch.

I have also created a branch with an upgrade to EventBus 3.0, but this requires more changes to the Squeezer code, so I don' recommend working from that.

**Comment by fhaertig** [comment]
Nice, i forked your repo just now. At least I can build it now and start working, thank you very much for looking into it :)

**Comment by nikclayton** [comment]
It's moot now, but per https://git-scm.com/book/en/v2/Git-Tools-Submodules, "git submodule init" and "git submodule update" needed to be run in the directory the first time you clone the project.
