### ISSUE TITLE
Next and previous buttons disabled on spotify playback

### ISSUE THREAD

**Issue by chau-intl** [nikclayton/android-squeezer#160]
When I have created a playlist using Spotify the next and previous button are disabled in the "playing now" window. This is not the case when playing local content. 
- If I go to the playlist window I can just press the next/previous/another song to start it (see first image). 
- If my device is locked the next button is enabled and works fine (see second image).

I'm using Squeezer 1.4.0.

![screenshot_2016-02-18-22-06-51](https://cloud.githubusercontent.com/assets/6311686/13158105/b9a063c6-d68b-11e5-8acf-83c7bfd89512.png)
![screenshot_2016-02-18-22-07-03](https://cloud.githubusercontent.com/assets/6311686/13158106/b9a352d4-d68b-11e5-82f2-87f5d1908abc.png)

**Comment by jcullen86** [comment]
I have the same issue using Spotify. Can't go forward or back from the "now playing" screen.

**Comment by gs11** [comment]
This applies for the Soundcloud app as well.

**Comment by matt-matt2** [comment]
I've seen this on BBC iPlayer listen again too. Coincidentally I've noticed that squeezer fails to get the right timing for the track when this happens (i.e. it gets a default "30 minutes" instead of the real program time. I'm told this is normal - until the program starts playing it doesn't know the time, but squeezer never refreshes its time). 
Next/prev works on the player itself.

**Comment by Gerrelt** [comment]
I've created a fix for this, tested with the spotify plugin.
See:

https://github.com/nikclayton/android-squeezer/pull/183/commits/1b87d415167e234e7b6a87804dede5bbbd6c604a

I hope these changes are accepted by the team.

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by nikclayton** [comment]
1.5.0 is released, which should fix this, so closing this issue. If you still see a problem, please re-open it.
