### ISSUE TITLE
Feature Request: edit main menu

### ISSUE THREAD

**Issue by Thomas-O** [nikclayton/android-squeezer#161]
I've been trying to create a network music player for my elderly (and easily confused) grandparent. After having tried and given up on Kodi, Chromecast and Neet Airstream, I've decided that Squeezebox is the way to go. However, I'm not convinced that my grandparent will be able to easily navigate their Squeezebox music library and radio streams via Squeezer. Please could you provide an option to edit and simplify the main menu. The following three options would make a great difference:
1. Hide main menu items - I would hide everything but genre and favourites.
2. Rename main menu items - I would rename genre as LIBRARY, and favourites as RADIO (streams).
3. Change / significantly increase the size of the main menu text. And possible that of sub-menus.

Thanks for your time.

_Thomas_

**Comment by kaaholst** [comment]
This should now be possible with CometD protocol. There's a duplicate issue which is tracking this #636. Please use that for future requests. Closing this
