### ISSUE TITLE
Context menu button too close to scroll bar

### ISSUE THREAD

**Issue by elParaguayo** [nikclayton/android-squeezer#162]
On my Galaxy S6, when I'm browsing items I like to click on the little triangle that opens the context menu ("Play", "Add to playlist", etc). The problem is that this is very close to the scrollbar so I often end up scrolling down the screen rather than opening the menu.

Can the distance be increased a bit?

It's not a deal-breaker for me it's just a bit frustrating at times.

**Comment by orclex** [comment]
I agree to that request. Maybe you could also exchange the triangle with an icon that shows the exact dimension a little better for touching with your finger on the context menu and not on the scroll bar?

**Comment by kaaholst** [comment]
Fixed in 2.0.0
