### ISSUE TITLE
multiple squeeze server support

### ISSUE THREAD

**Issue by csrhodes** [nikclayton/android-squeezer#163]
I have one slimserver at home, and one at work.  At the moment, I have to edit the server settings each time I change location; it would be nice if squeezer could support storing settings for multiple servers, and allow to switch between them on the start screen.

**Comment by kaaholst** [comment]
That should already work. Squeezer associate the server settings with the wireless network the phone is connected to, so it should be able to connect to the proper server.

Could you provide some more details so I am able to help you with this?

**Comment by csrhodes** [comment]
Hi!

My apologies: I had an outdated version of squeezer installed, from a previous development / test cycle.  I've reinstalled and based on minimal testing things seem to work.  I'll do a bit more testing over the next couple of days (as I move from location to location), but I'm happy for this issue to be closed if that suits.

Thanks,

Christophe

**Comment by nikclayton** [comment]
Closing for the time being. If you do see the problem recur please do re-open this issue. Thanks.
