### ISSUE TITLE
Now playing context menu?

### ISSUE THREAD

**Issue by somethingunused** [nikclayton/android-squeezer#166]
Hi. I think this is a feature request.
In the logitech controller app, there was a context menu in the now playing screen, from long press of the artwork. This appears to be the only way to access, in my case, the radio paradise PSD plugin. Can this be done in squeezer 1.4, and if not not could it be considered for inclusion?

**Comment by kaaholst** [comment]
I think this should be available in Squeezer now, so closing this.
If not please reopen.
