### ISSUE TITLE
Remote Music Libraries

### ISSUE THREAD

**Issue by kanyi** [nikclayton/android-squeezer#167]
There is a plugin in the LMS "Remote Music Libraries ". With these I can access other LMS servers and UPnP servers/clients. It is working well, but I can not see these option in the android-squeezer. (Home/My Music/Remote Music Libraries) It would be nice to see these option on my phone.

**Comment by MRalser** [comment]
same here, is there a possibility to access remote Music libraries?

**Comment by kaaholst** [comment]
Fixed in 2.0.0
