### ISSUE TITLE
Feature request: change download target directory for music

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#168]
Hi,

it would be great to change the download target directory for music downloaded from the squeeze server. Default is the internal smartphone disk but it would be great to change it to an additional sdcard with more free space. Maybe it would be possible to change the directory name for downloaded music too.

Thank you very much!

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by orclex** [comment]
Thanks, it is working good. 
Is there a reason why you cannot choose the directory (to use directory "music" on SDCard)?

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
