### ISSUE TITLE
Feature request: show artist name from current playing song in playlist view

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#169]
Hi,

when I add several albums to a playlist I see the current playing song below the playlist. But only the name of the album and the trackname is shown - not the name of the artist. Please add the artist name to the current playing song in the playlist view.

Thank you very much!

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.
