### ISSUE TITLE
Feature request: add play next song button in playlist view

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#170]
Hi,

can you please add a play next song button next to the pause button in the playlist view (the panel current playing song)?

Thank you very much!

**Comment by matt-matt2** [comment]
Agreed, it would be good to replicate both next and prev on this view.

**Comment by nikclayton** [comment]
I've added this to tablets (portrait and landscape mode) and phones (landscape mode), which I think helps.

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.
