### ISSUE TITLE
increase cache size for long playlist with album art

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#171]
Hi,

I have many albums, all with cover images. Scrolling down a huge list is very slow and stuttering on my devices. It needs some time to show song information and cover images. Now scrolling up some pages it needs some time again to show the covers not in cache anymore. Maybe you can increase the local cache size and cache more cover images until the squeeze server rescans its files. If there is enough space on the device for cover cache, squeezer does not have to download the cover images every time from the server when opening the album list.

Thank you very much!

**Comment by nikclayton** [comment]
Seems reasonable. I've just put in a change to use either 100MB for the disk cache (10x more than current), or 2% of the usable space on the device, whichever is smaller.

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by nikclayton** [comment]
1.5.0 is released, which should fix this, so closing this issue. If you still see a problem, please re-open it.
