### ISSUE TITLE
Feature request: play song after current song and return back to playlist

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#173]
Hi,

it would be great to to have an additional menu entry for songs: play song after current song and return back to playlist
Multiple songs added should create a new queue for songs played one after another before returning to the original playlist.

Thanks and best regards,
Alexander

**Comment by matt-matt2** [comment]
Hmm, seems to me that this is exactly what "Play after the current song" does in squeezer today, no?
