### ISSUE TITLE
Feature request: show artist name on lock screen widget

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#174]
Hi,

when playing my favourite radio station there is a squeezer widget on the android lock screen showing an icon, title, the device name that is playing, a pause and a next button.
When I open the app I can see that the album is "unknown", what is ok for radio streams and not necessary to show but the artist name tag is also set and it is known. Why is the artist name not shown on the lock screen widget above the track name?

Please add the artist name to the lock screen widget!

Thanks a lot!

Regards,
Alexander

**Comment by kaaholst** [comment]
Fixed in 2.0.0
