### ISSUE TITLE
Can't change the radio station for alarms

### ISSUE THREAD

**Issue by PatrickHonorez** [nikclayton/android-squeezer#175]
Hi, if I try to change the radio  station for an alarm. Whatever selection I chose, it always comes back to 'current playlist'.  
Also when opening alarm's list, only the first one appears then message 'Loading'.  
If I touch the screen, I can then see the other alarms.
Using a Huawei P20 Pro, in fullscreen mode.

**Comment by mitch-geht-ab** [comment]
Hi,
similiar problem on my phone.
I've defined 2 Alarms via WebIF of my Logitech Mediacenter. When I want to edit thema via Squeezer 1.4.1 it shows only Alarm1 with the correct time but with an empty Playlist and Alarm2 isn't shown.
After touching somewhere on the screen Alarm2 appears. But I can't change anything. Can select another Alarmsound or Playlist but it isn't saved.
See attached screenshots.

![screenshot_20161102-152803](https://cloud.githubusercontent.com/assets/8008251/19932740/62ce4152-a111-11e6-8049-9043052876ee.png)
![screenshot_20161102-152810](https://cloud.githubusercontent.com/assets/8008251/19932741/62d306d8-a111-11e6-8b24-385feec90d5e.png)

**Comment by kaaholst** [comment]
This should be fixed since version 2.0.0, so closing this. If not, then  please reopen
