### ISSUE TITLE
Artists view shows songwriters/composers

### ISSUE THREAD

**Issue by Sciamano72** [nikclayton/android-squeezer#176]
Hello,
I am running LMS v7.9 on a raspberry pi.
When I connect to it using Squeezer, and select the Artists "button", it does not show the actual bands/singers but a list of the songwriters/composers.

The image is worth a thousand words.

![lms3](https://cloud.githubusercontent.com/assets/22921419/19494938/a30cce82-9581-11e6-8fc1-5a22bb9e0573.png)

What's wrong? Thanks

**Comment by kaaholst** [comment]
Fixed in 2.0.0
