### ISSUE TITLE
Squeezer don't see Squeezeboxes

### ISSUE THREAD

**Issue by befast** [nikclayton/android-squeezer#178]
Hi,
I setup LMS 7.9.0 on Raspbian (on PI 2) and 2 PiCorePlayers (on PI 3).
I see the LMS PiCorePlayers on the LMS web interface.
The LMS is seen by in the Squeeze Controller Android App but not in the Squeezer App, however LMS is detected.
I try with the LMS 7.7.5 on Windows and I see the LMS and the PiCorePlayers on the Squeezer App.

Any idea what's wrong ?

Thanks in advance

**Comment by austins68** [comment]
How bizarre!

I think you have just raised exactly the same issue I did.  I don't understand why I couldn't see yours when I was creating mine shortly afterwards.  See #179.  I also have a workaround that works for me.  I'll add it to the description.

**Comment by befast** [comment]
You're right austins68, it works !
Thanks a lot for your help.
