### ISSUE TITLE
Squeezer 1.4.1 cannot list players on LMS 7.9

### ISSUE THREAD

**Issue by austins68** [nikclayton/android-squeezer#179]
I have had to upgrade to LMS 7.9 because of a ReadyNAS firmware upgrade.  My Squeezer app stopped working at that point: it was unable to enumerate my players (actually only one).  It works with LMS 7.7.

By experimenting, I was able to determine that the problem was that the reply to the initial CLI query "players 0 20 full_list:1" has changed between 7.7 and 7.9.

- **LMS 7.7** replies "players 0 20 full_list:1 count:1 playerindex:0 playerid:xx:xx:xx:xx:xx:xx uuid: ip:192.168.x.x:xxxx name:xxxxxxx model:squeezelite isplayer:1 displaytype:none canpoweroff:1 connected:1"
- **LMS 7.9** replies "players 0 20 full_list:1 count:1 playerid:xx:xx:xx:xx:xx:xx uuid: ip:192.168.x.x:xxxxx name:xxxxxxx seq_no:0 model:squeezelite modelname:SqueezeLite power:1 isplaying:0 displaytype:none isplayer:1 canpoweroff:1 connected:1 firmware:v1.8"

Looking at the Squeezer code, I had a hunch that the "playerindex" parameter was important.  I patched the function __addPlayersLoop_ in /usr/share/perl5/Slim/Control/Queries.pm on my LMS 7.9 to include the parameter, and this did indeed enable Squeezer to work.

I'm leaving this workaround in place, but the correct fix is probably to allow Squeezer to cope without the "playerindex" parameter.

I think this is a problem with interop with LMS 7.8 as well.

**UPDATE**:  Here is a diff for the patch to the above-mentioned file, /usr/share/perl5/Slim/Control/Queries.pm.  My version is _7.9.0 - 1479378558_.  This worked for me, but I offer no warranty.  Apply this _**at your own risk**_ and then restart your LMS service.

```
*** a/Queries.pm        2016-11-20 21:23:43.549509849 +0000
--- b/Queries.pm        2016-11-20 21:24:56.434742441 +0000
***************
*** 2346,2351 ****
--- 2346,2353 ----
        if (scalar(@players) > 0) {

                for my $eachclient (@players[$start..$end]) {
+                       $request->addResultLoop('players_loop', $cnt,
+                               'playerindex', $cnt);
                        $request->addResultLoop('players_loop', $cnt,
                                'playerid', $eachclient->id());
                        $request->addResultLoop('players_loop', $cnt,

```

**Comment by matt-matt2** [comment]
As per comments in the thread over on the Slimserver forums this was an oversight by the maintainers of LMS and this field has been reinstated in the latest nightly build.
