### ISSUE TITLE
Squeezer connects to SqueezeBox LMS but has no control over

### ISSUE THREAD

**Issue by vrho** [nikclayton/android-squeezer#180]
Hi, 

I'm using Squeezer 1.4.1 with Max2Play SqueezeBox LMS Nightly 7.9. Since yesterday my Squeezer normaly connects to SqueezeBox, but I can only search trough my music library. I can't control my SqueezeBox Server. I can't add songs to play, my Now playing (when I add a song trough webadmin) shows "Unknown track", "Unknown album" and "Disconnected."; where the play and pause button was, there is a green dot.  

Thank you for your help.

**Comment by kaaholst** [comment]
I think this is caused by a bug in the nightly build of LMS. According to issue [179](https://github.com/nikclayton/android-squeezer/issues/179), it should be solved now, if you upgrade to the latest build of LMS.,

**Comment by mavit** [comment]
I experienced these symptoms and can confirm that they were fixed by updating to the latest nightly.
