### ISSUE TITLE
IPadress lossed with no internet connection

### ISSUE THREAD

**Issue by Kclemen** [nikclayton/android-squeezer#182]
Every now and then the app loses the configured IPadress when the app is openend when there is no internet access. Would it be possible to always remember the configured IPadress?

**Comment by matt-matt2** [comment]
It does always remember.. or it should. But when it joins a "new" wifi it will need to rescan for a server which should take no more than a second or two.

**Comment by Kclemen** [comment]
Did you try to open the app without wifi connection? The app always forgets the configured IP.
Problem is that I'm sometimes too fast with opening the app when I come home. My mobile phone (huawei p8 lite) connects after several minutes...

**Comment by matt-matt2** [comment]
Yeah, it sits and waits until a connection is found, then it reconnects straight away. I have never manually selected or "saved" my connection details, it's just using the details it detected the first time I ran it. Can you grab some screen shots to show what you mean?

**Comment by TheOriginalOrthonormal** [comment]
I am getting similar behavior.  I use Squeezer to connect to my home server and play music through SqueezePlayer when I am on a remote network.  I also use it to control the local players when I am at home.    

Squeezer forgets the server address and password occasionally.  It seems to happen when I switch between the home network (LAN that the slimserver is on) and a remote network (cellular connection or WiFi when not at home).  I can use the named internet address [myserver.com:9090] to connect from any location, so it would be really convenient if Squeezer didn't clear the address and password information when I join a different network.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue. 

Thank you!
