### ISSUE TITLE
Coloured triangle on artwork

### ISSUE THREAD

**Issue by elParaguayo** [nikclayton/android-squeezer#185]
I've downloaded and built the [Spotify search pull request](https://github.com/nikclayton/android-squeezer/pull/184) and I've noticed that there are coloured triangles in the top left corner of the artwork. Is there any reason for these?

I don't think it's related to that specific pull request.

Can someone tell me where this is in the code so I can remove them.

**Comment by Flautz** [comment]
Try switching the build configuration from "debug" to "release". I've seen some green and red dots next to every picture in debug configuration which are gone in release configuration - maybe that's your issue.

**Comment by elParaguayo** [comment]
Perfect. That fixed it. Thank you.

**Comment by nikclayton** [comment]
Yes, in the debug configuration those indicate whether the image was served from the in-memory cache, the disk cache, or had to be fetched from the network.
