### ISSUE TITLE
Youtube search

### ISSUE THREAD

**Issue by Denguido** [nikclayton/android-squeezer#190]
I've been trying out the Squeezer app (android) and whenever I go to the Playlist search option under the youtube plugin it only shows me a (seemingly) random list of playlists, and filling out the search box at the top only gives me results from my own media (not youtube results). Is there a possibility to search in the youtube plugin?

**Comment by fishbone2017** [comment]
Dear Nik Clayton,
first of all, thanks for your great app and development.
I have the same issue as Denguido.
In the LMS web interface, I can perform a youtube search by hovering over each menu item and typing the search term in the appearing search bar on the right of the line.
Unfortunately, this doesn't seem to work in your app, as this only shows the menu items, but not the correpsonding search bar.

So, I would really appreciate if you could implement this feature.
![youtube menu](https://cloud.githubusercontent.com/assets/26121658/23476005/8aca9cea-feb9-11e6-8dad-8fcb9af8ff66.jpg)

**Comment by kaaholst** [comment]
Hi and thanks for the feedback.

Youtube search will be available in the next version of Squeezer, which will be released shortly. We hope you like it.

**Comment by nikclayton** [comment]
I've just released this in the first beta of 1.5.0. You can sign up to receive the beta versions at https://github.com/nikclayton/android-squeezer/wiki/Beta-testing.

**Comment by nikclayton** [comment]
1.5.0 is release, which should fix this, so closing this issue. If you still see a problem, please re-open it.
