### ISSUE TITLE
Inefficient API is used

### ISSUE THREAD

**Issue by struggggle** [nikclayton/android-squeezer#192]
Dear developers,

I found an inefficient API, setImageResource(), is widely used in squeezer.

For setImageResource(), Google says this:
https://developer.android.com/reference/android/widget/ImageView.html#setImageResource(int)
" This does Bitmap reading and decoding on the UI thread, which can cause a latency hiccup. If that's a concern, consider using setImageDrawable(android.graphics.drawable.Drawable) or setImageBitmap(android.graphics.Bitmap) and BitmapFactory instead. "

I noticed that in the following code, setImageResource() is used:
https://github.com/nikclayton/android-squeezer/blob/master/Squeezer/src/main/java/uk/org/ngo/squeezer/itemlist/PlayerView.java#L70

https://github.com/nikclayton/android-squeezer/blob/master/Squeezer/src/main/java/uk/org/ngo/squeezer/VolumePanel.java#L176

https://github.com/nikclayton/android-squeezer/blob/master/Squeezer/src/main/java/uk/org/ngo/squeezer/IconRowAdapter.java#L105

https://github.com/nikclayton/android-squeezer/blob/master/Squeezer/src/main/java/uk/org/ngo/squeezer/itemlist/AlbumArtView.java#L54

https://github.com/nikclayton/android-squeezer/blob/master/Squeezer/src/main/java/uk/org/ngo/squeezer/itemlist/AlbumArtView.java#L54

https://github.com/nikclayton/android-squeezer/blob/master/Squeezer/src/main/java/uk/org/ngo/squeezer/itemlist/MusicFolderView.java#L68

Do you think the use of setImageResource() will affect squeezer's performance? If so, maybe we should move Bitmap reading and decoding to a background thread.

Thanks.

**Comment by nikclayton** [comment]
It's theoretically a possibility, although I don't recall it ever showing up when I've done informal benchmarking of various bits of Squeezer.

It wouldn't be a bad project to try if you wanted to experiment with making a change and getting it submitted, if that's interesting.

The right way to do it is probably to extend the ImageWorker class with a new loadImage() method that reads the image from a resource in another thread and then updates the UI. ImageWorker.java already contains the code to do the heavy lifting of thread management and so on.

Is that something you'd like to try?

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
