### ISSUE TITLE
Previous and next track only possible while playing

### ISSUE THREAD

**Issue by ghost** [nikclayton/android-squeezer#195]
It doesn't seem to be possible to switch to the previous or next track while the playback is paused.

**Comment by fri-sch** [comment]
I have a hacky solution for this here: https://github.com/fri-sch/android-squeezer/tree/skip_tracks_when_not_playing

The next/previous track seems to autoplay, so I had to stop the track after switching if track was not playing before.

I don't know if this solution is appropriate, but I find it quite useful to be able to skip through a list of tracks with the next/previous buttons without actually playing the tracks.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue. 

Thank you!
