### ISSUE TITLE
Be less intrusive with the volume tip

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#197]
The volume tip shouldn't appear when the app is first installed, since that's intrusive. Better if it showed up after the user has used the volume menu item, but only if they haven't already used the hardware controls.

**Comment by matt-matt2** [comment]
Funnily enough I saw a comment from a user on a forum recently stating that they hadn't realised the device volume buttons controlled the volume.. I do agree it can be made less intrusive however. Smaller and disappears more smoothly.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
