### ISSUE TITLE
Binder.java

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#205]
#### in android.os.BinderProxy.destroy

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/squeezer/android/apps/uk.org.ngo.squeezer/issues/58dc01c10aeb16625bff0204](https://fabric.io/squeezer/android/apps/uk.org.ngo.squeezer/issues/58dc01c10aeb16625bff0204)

**Comment by nikclayton** [comment]
Stack trace:

```
Fatal Exception: java.util.concurrent.TimeoutException: android.os.BinderProxy.finalize() timed out after 10 seconds
       at android.os.BinderProxy.destroy(Binder.java)
       at android.os.BinderProxy.finalize(Binder.java:459)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
       at java.lang.Thread.run(Thread.java:841)
```

Nothing Squeezer can do about this.

**Comment by MrVlad001** [comment]
> Stack trace:
> 
> ```
> Fatal Exception: java.util.concurrent.TimeoutException: android.os.BinderProxy.finalize() timed out after 10 seconds
>        at android.os.BinderProxy.destroy(Binder.java)
>        at android.os.BinderProxy.finalize(Binder.java:459)
>        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
>        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
>        at java.lang.Thread.run(Thread.java:841)
> ```
> Nothing Squeezer can do about this.

Any solutions ?
