### ISSUE TITLE
Handle favorites as songs

### ISSUE THREAD

**Issue by guillaumezin** [nikclayton/android-squeezer#213]
Hello,

Thank you for this very handy application. May i suggest to make possible to handle favorites as songs, meaning that you could press on a favorite and have selection action or launch the chosen default action, without having to press the little triangle on the right but by pressing anywhere on the line, it would be easier.

Thank you again.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
