### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by zuglufttier** [nikclayton/android-squeezer#227]
First of all: android-squeezer is the best remote control for me, even the apps you have to pay for are not better: So thanks a lot for your effort!

But squeezer used to be supported in f-droid and is no longer: https://f-droid.org/repository/browse/?fdid=uk.org.ngo.squeezer

Can google analytics and other proprietary parts be completely deactivated?

**Comment by nikclayton** [comment]
Hi, thanks for the feedback.

In theory, this could be done as another build variant that either pulled in a stub library for Google Analytics (and, probably the Crashlytics library as well) following the details in https://developer.android.com/studio/build/build-variants.html.

In practice, that's way down my list of priorities I'm afraid. If anyone else reading this wants to take a stab at  it and contribute a pull request I'll definitely take a look.

**Comment by zuglufttier** [comment]
Thanks for your answer! Well, maybe I'll have a look into this myself... Never worked on an android app before but there's always a first time for something.

**Comment by eisengrau** [comment]
Sorry for reviewing this. But I do have to agree, Squezzer is the best, and so far the only open-source app to control Squeezebox. The F-droid version currently in the archive is extremely outdated, albeit it works... Is it possible to, if not add a new version to F-droid, to release a binary, installable APK, for us folks who have LineageOS or in general refuse to have/use Google services on their devices?

**Comment by mondopi** [comment]
I'd like to second this. Please consider bumping this up your list of priorities as there are no google-free google-less-android controllers. Loving the controller so far...

**Comment by lord-aerion** [comment]
Wondering if @IzzySoft would consider maintaining an F-Droid build?

**Comment by IzzySoft** [comment]
Unlikely, as he's no developer nor packager. But if there would be APKs attached to the tags/releases (preferably without Crashlytics etc), he might consider feeding them to his repo :wink:

**Comment by kaaholst** [comment]
I think proper inclusion in F-Droid as possible by now, and it's on the to-do list. We haven't been able to put a release on f-droid for a long time because we were using Google Analytics and Crashlytics (proprietary tracking/analytic dependencies). We don't use these any more for other reasons, so it should be possible to put a new version on f-droid.

**Comment by IzzySoft** [comment]
@kaaholst so maybe start attaching an APK? The library scanner in my repo could give you some clues then.

**Comment by lord-aerion** [comment]
This is really good news. I'm trying to replace as many apps as possible with F-Droid versions, in the hope of one day being able to end my reliance on the Play Store and run a de-Googled phone.

**Comment by kaaholst** [comment]
Squeezer is now available on F-Droid, so closing this.
https://f-droid.org/en/packages/uk.org.ngo.squeezer/
Thanks for the suggestion.
