### ISSUE TITLE
use Bluetooth Speaker button controls

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#265]
Hi,

I connect my Bluetooth Speakers (JBL Charge 3) with my Android device running squeezeplayer and squeezer.
The speaker has buttons like volume, pause and next that submit its signal by Bluetooth to the android system. Volume is working but pause and next is not. Is it possible for squeezer to get these button events and react appropriate?

BTW: Vol+ and Vol- steps are much to large. I'm not sure if you can handle this or if it is up to android system only. But it would be great to half the step for each vol+ or vol-.

Thanks!

**Comment by niclan** [comment]
Does "pause" and "next" work with other audio players on your phone?

**Comment by orclex** [comment]
Yes, it does work! I can stop/start and skip music with my default music player. If you tell me how to get these button IDs I can help...

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
