### ISSUE TITLE
Add "Play from here" as a possible setting for the "song select action"

### ISSUE THREAD

**Issue by jtl5770** [nikclayton/android-squeezer#266]
Hi,

my usual habit when looking for music is browsing through the albums, clcking on them (action is set to "browse" as album select action). Then I just choose the first song I want to listen to, but expect the album to continue from there on.

Actually, the option to "Play from here" from the dropdown does exactly what it should, putting the whole album into the playlist, but starting with the selected song and carry on afterwards.

The only this that is missing is having this option in the settings as a default for the song select action.

**Comment by kaaholst** [comment]
This is possible now via the Player screen and the 3-dot menu to the right of the player.
