### ISSUE TITLE
squeezer hangs after android sleep/standby

### ISSUE THREAD

**Issue by orclex** [nikclayton/android-squeezer#270]
Hi,

I'm running squeezplayer and squeezer on android 7.1. When I pause the current playing radio channel and return after some hours I cannot resume playing the radio channel. After pressing the play button nothing happens. I can go back in the folder hierarchy but it does not play anymore. I think squeezer has lost the connection after android sleep/standby mode but it does not recognize it and it does not restore the connection automatically. I have to kill the app squeezer, start it to connect again and then it is playing!

**Comment by kaaholst** [comment]
Fixed in 1.5.4 which supports Android foreground service
