### ISSUE TITLE
Searching in the spotify app only returns artists

### ISSUE THREAD

**Issue by chau-intl** [nikclayton/android-squeezer#291]
When I search within the Spotify App in Squeezer 1.5.1 (android 6 & 7), the search result looks like the following:

Artists
1. result
2. result
...
x. result

The results are okay but I miss the Song, Album and Playlist results.

Performing the same search within the LMS web interface gives me the expected results and not just the Artists.

It might be related to Spotify stopped supporting the libspotify library previously used by LMS Spotify plugins and I have switched to the Spotty plugin which uses a different library. I think that is the only change I have made in a while.

**Comment by kaaholst** [comment]
Hhmm... sounds stange
It works for me (LMS 7.7.2).
You can try the filter function from eg. the Album list, it uses the same internals as the search function.
Select the Album list / Menu / Filter, and fill in the search text. Results here shall be the same as you get from using the search function. If this doesn't work, my guess is that this is a server issue.

**Comment by chau-intl** [comment]
Hi Kurt, I am on LMS 7.9.0. 

You mention a filter function I can try, but I cannot find it.
In the root I have "My Apps" / "Spotty" / "Search" and that is the one giving incorrect results. I have "My Apps" / "Spotty" / "Albums", but I cannot do anything in there. Can you guide me a bit further?

**Comment by kaaholst** [comment]
- From  the start page select Albums
- From the menu select Filter
- Fill in a search string and select Ok

I have attached some screenshots, which hopefully are informative.

In the meantime I will fire up a 7.9.0 server, to see if we have an issue with that.

![root](https://user-images.githubusercontent.com/428304/28501784-7efe6478-6fe3-11e7-94fd-2c6b1d104158.png)
![albums](https://user-images.githubusercontent.com/428304/28501785-839ee7f0-6fe3-11e7-95ab-47ccde451e64.png)
![filter](https://user-images.githubusercontent.com/428304/28501787-936a61e6-6fe3-11e7-9f2c-d33987cac66d.png)

**Comment by kaaholst** [comment]
I just did some limited testing, and it seems to work. Results are different from the older server, so I guess the search algorithm has changed. The results are consistent across Squeezer and the web-interface though.

**Comment by chau-intl** [comment]
Hi Kurt, thank you for the clarification. But my searching is done within the Spotify app (Spotty) as seen here and I only get to search within artists here:

![1](https://user-images.githubusercontent.com/6311686/28540482-dcdcba54-70b5-11e7-9d5e-e0feb40a9fb9.jpg)
![2](https://user-images.githubusercontent.com/6311686/28540483-dce36a48-70b5-11e7-9e22-9418adb04b07.jpg)
![3](https://user-images.githubusercontent.com/6311686/28540480-dcd717d4-70b5-11e7-917e-58278e82a6f7.jpg)
![4](https://user-images.githubusercontent.com/6311686/28540478-dcd3c8f4-70b5-11e7-80ae-63949ffcf6eb.jpg)
![5](https://user-images.githubusercontent.com/6311686/28540479-dcd4cca4-70b5-11e7-865d-4971e03ad9fe.jpg)
![6](https://user-images.githubusercontent.com/6311686/28540481-dcda93a0-70b5-11e7-9103-c2b488a26495.jpg)

**Comment by kaaholst** [comment]
Oops, I should have read your issue properly in the first place.

Squeezer currently uses the CLI protocol when communicating with LMS. We are working on a switch to the comet protocol, which should provide better support for things such as plugins. Until then your mileage may vary.

**Comment by chau-intl** [comment]
Well I look forward to beta test the upcoming protocol switch. Thanks for taking the time to reply!

**Comment by psaffrey** [comment]
I have a related problem that when I create a search with Spotty, it returns artists (as shown above) but when I select the artist I always get a blank screen. No error message is presented. If I use Spotty search through the web client it works fine. 

Should I expect this to be fixed by the protocol upgrade as well? When is that expected?

Thanks for the great app - I use it every day :)

**Comment by kaaholst** [comment]
This is fixed in 2.0.0 so closing this
