### ISSUE TITLE
Remember playlist scroll position when deleting/manipulating contents.

### ISSUE THREAD

**Issue by matt-matt2** [nikclayton/android-squeezer#298]
If the playlist is longer than a single page and you scroll from the current playing position to e.g. "Remove from playlist" a track on the next page, when the dialogue is completed it snaps back to the current playing position, not the last scroll position. This makes managing a live playlist quite tedious if you want to remove just a few items. There are probably other operations where it would make sense to stay where it was left too, whilst I accept there are some operations where "snap to play position" also makes sense.

It would be cool to have a quicker "remove from playlist" action, e.g. a swipe right with temporary "undo" button, which seems to be a common method these days. I vaguely recall seeing this requested elsewhere too, but can't find it now.

**Comment by kaaholst** [comment]
This is fixed in Squeezer version 2.2.1 and newer, closing.
