### ISSUE TITLE
Add tracks to an existing playlist

### ISSUE THREAD

**Issue by Denguido** [nikclayton/android-squeezer#326]
Hello,

Should it be made possible when you have a number of tracks in your playlist not only to save them in a new playlist (as it is already possible today) but add them to an existing playlist that was created before?
If possible also per track. In this way you can add a track to any existing previous saved playlist.

This should be a huge improvement I think.

Kind regards,
Thierry David

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
