### ISSUE TITLE
In player screen: Volume control changes volume of wrong player

### ISSUE THREAD

**Issue by mdrie** [nikclayton/android-squeezer#337]
Hi Nik,
we use the app for quite some time. (years?) Really happy! Thanx.

One thing annoys us: We have 3 players. Two of which are squeezelite (Raspberry Pi). When changing the volume on one of them in the player screen, sometimes the volume of the other one is changed.

Details:
- After tapping on the volume bar of player A there is instant visual feedback by a change of the volume bar of the player A.
- Less than a second after that, the volume of player B changes and the bar of player A changes back to the original setting and the bar of player B changes to the new setting instead.
- Sometimes the same happens in reverse with B - then there is a "workaround". Sometimes B will change B...

Regards,
Mathias

**Comment by kaaholst** [comment]
This is fixed in 2.0.0 so closing this
