### ISSUE TITLE
No players in squeezer

### ISSUE THREAD

**Issue by rmbzz** [nikclayton/android-squeezer#367]
I have a working squeezebox setup with logitechmediaserver 7.9.0 running on ubuntu 16.04 and six players. 

I recently moved my server from one machine to another and one doing this, the players disappeared from squeezer.  

Do you have any suggestions for troubleshooting this problem?  When it works, squeezer has been great.

**Comment by kaaholst** [comment]
First make sure that Squeezer is connected to the right server. Select disconnect (from the main menu), then select the new server from the list of servers.
Note if your players comes up in Squeezer when Squeezer is connected to the old server, you have to move them to the new server. (this can't be done from Squeezer).

If this fails I think we once had an issue  with the player list on recent server, so check that you are running the latest version of Squeezer. Select about from the main menu, and verify that it is the same version as on Google Play.

Hope this helps

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue. 

Thank you!
