### ISSUE TITLE
Artwork issue with Qobuz

### ISSUE THREAD

**Issue by arnomx** [nikclayton/android-squeezer#371]
I am using Qobuz through the dedicated LMS plugin ; artwork is well shown in Squeezer while browsing available albums from Qobuz, but once tracks are selected for playing, no album art is displayed in both playlist and "Now Playing" views ; they are displayed in LMS though. This issue does not occur with Deezer or my local music.

**Comment by kaaholst** [comment]
Fixed in 2.0.0.
