### ISSUE TITLE
Show player display

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#38]
```
The "display ? ?" command fetches whatever the player is currently showing.

The app could do this and show it somewhere in the UI.
```

Original issue reported on code.google.com by `nik@ngo.org.uk` on 2011-09-03 08:12:50

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
