### ISSUE TITLE
Actions buttons are too small

### ISSUE THREAD

**Issue by alexanderadam** [nikclayton/android-squeezer#408]
The current release of Squeezer has just a small button. Besides from being small it's low contrast doesn't help neither. :wink: 

![screenshot_20180806-145856_squeezer](https://user-images.githubusercontent.com/372620/43717966-7a3e3e9c-9989-11e8-879a-db41c6ddc5aa.jpg)

Besides from #227 this is the only issue I have.

PS: Thank you sooo  much for maintaining Squeezer! I really appreciate it! I hope I can pay you a beer some day.
PPS: System language is en-gb and it is "Favourites" in overview but "Favorites" in detailed view.

**Comment by kaaholst** [comment]
Fixed in 2.0.0
