### ISSUE TITLE
Browse modes, json-rpc

### ISSUE THREAD

**Issue by davidaturton** [nikclayton/android-squeezer#413]
Squeezer's home screen doesn't duplicate the browse modes I set up in LMS/Additional Browse Modes (I find browse by composer really useful). There have been related requests and I think this might be a CLI limitation. If that is the case, will Squeezer ever implement json-rpc?

Anyway, great thanks for the exceptionally nice app.

**Comment by kaaholst** [comment]
Fixed in 2.0.0
