### ISSUE TITLE
Squeezer does nothing but ask for login

### ISSUE THREAD

**Issue by Gresyth** [nikclayton/android-squeezer#416]
I installed Squeezer on my new Motorola motoe5 cruise and it keeps asking for a login. max2play running the server on an rPi-3b over wifi. 
My server works fine from Firefox on my PC. My old phone had Android 5 and everything worked fine.

**Comment by kaaholst** [comment]
Connection is changed with the switch to CometD from version 2.0.0 so this is hopefully fixed. If not then please repost,
