### ISSUE TITLE
Support config backup

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#43]
```
Android has APIs to backup configuration data so if the phone is reset or the user signs
in to a different phone the configuration follows them.

We should do that.
```

Original issue reported on code.google.com by `nik@ngo.org.uk` on 2011-09-18 10:36:14

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new issue if you still request this.

Thank you!
