### ISSUE TITLE
Be able to copy titles of what's playing

### ISSUE THREAD

**Issue by aswen** [nikclayton/android-squeezer#440]
Hi, I took this screenshot while I was listening to an internet radio station and heard music I wanted to listen more of. I would have liked to be able to select the text and copy-paste that to search on the internet for more of the same artist, or his/hers website.

Would it be possible to make this text "selectable"?

![screenshot_20181120-002633](https://user-images.githubusercontent.com/550440/54016952-d5cd4980-4184-11e9-9484-2ac61346d4cf.jpg)

Thanks by the way for this great tool. I use it every day!

**Comment by kaaholst** [comment]
This is fixed in 2.2.2 where the Now Playing screen is interactive.

Please reopen if this is not the case.
