### ISSUE TITLE
Question: lyrics

### ISSUE THREAD

**Issue by nilskp** [nikclayton/android-squeezer#546]
Latest version (1.5.3) states

> Show lyrics if provided by the server.

What is required for this to work? I use the latest official LMS and have `.txt` files with name identical to track file (typically `.flac`). Do I need another scheme?

**Comment by kaaholst** [comment]
I use [lyrico](https://github.com/abhimanyuPathania/lyrico) to download the lyrics.
This embed the downloaded lyrics into the song (as standard lyrics tag) and also save it to a text file.
I am not sure but, I think LMS uses the embedded lyrics.
Hope this helps

**Comment by nilskp** [comment]
@kaaholst If LMS only uses embedded lyrics, it won't work for me. I can't seem to find this documented anywhere though.

**Comment by kaaholst** [comment]
Neither can I. Perhaps the [forum](https://forums.slimdevices.com/) or the [wiki](http://wiki.slimdevices.com/index.php/Main_Page) can help?

When Squeezer gets full plugin support, there may be a plugin to provide the requested functionality. I think for example the Song Lyrics plugin retrieves lyrics "on the fly".

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
