### ISSUE TITLE
Feature request: Android TV

### ISSUE THREAD

**Issue by danielWQ** [nikclayton/android-squeezer#586]
With the current version in the Play Store the Android-TV device is marked as unsupported device for this app. It would be nice to have this great app on Android-TV, too.

**Comment by Braklet** [comment]
+1 for adding the Android TV OS variant.  Squeezer is my favorite Android controller app by far, it would be great to be able to run it natively on my nVidia Shield or the growing number of televisions running Android TV.  I'm willing to pay a bounty for this feature, in fact.

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/587](https://github.com/kaaholst/android-squeezer/issues/587)

Please use that for future comments.
