### ISSUE TITLE
Feature requests: Wake-On-LAN and Last.FM Loves

### ISSUE THREAD

**Issue by mj00000** [nikclayton/android-squeezer#615]
hi and thanks for a fantastic product that my family and i use every day. nice to use, good looking and reliable

i hope this is an acceptable way of requesting new features? i've never used GitHub before so sorry if this is the wrong way of doing it

two things would make this app even more amazing:

1. the ability to wake the Logitech Media Server from the app (as you can with the physical Remote Control for any of the SqueezeBoxes) when the server is in standby/hibernation

2. the ability to "Love" tracks on Last.FM if the Last.FM plugin is installed, configured and is actively scrobbling

many thanks!

**Comment by kaaholst** [comment]
This is the proper place to request features and report issues, thank you.

Squeezer version 2.0.0 will be released shortly. It implements the CometD protocol so all plugins and menus should be supported. Hopefully the same goes for these two. Otherwise please report back.

**Comment by mj00000** [comment]
thank you

**Comment by mj00000** [comment]
hi. Squeezer version 2.0.0 looks like it is going to be excellent!

hope it is fine that i give some feedback in the name of making the product even better:

- i can confirm that "loving" the track on Last.FM works which is fantastic so thanks for that
- as far as i can determine, attempting to connect to the Windows LMS server when it is in standby or hibernate unfortunately does not wake the server, as it does when one does the equivalent action using the physical remote control on the physical SqueezeBox v3 player
- lastly this is probably not a big deal for most users and i will adjust my usage patterns to accommodate but i just want to make the small point that is to lament the "download" feature that was in Squeezer prior to version 2.0.0. not sure if many others used this but i found it great to be listening to an album and being able to tap the phone screen to download the tracks to the phone, thereby allowing me to take the music on the go and continue listening


many thanks

**Comment by kaaholst** [comment]
Download is handled in #621 so closing this

**Comment by kaaholst** [comment]
Wake-On-LAN is now tracked by a new request #657
