### ISSUE TITLE
Feature request: Setting for choosing tiles or list.

### ISSUE THREAD

**Issue by bitwit42** [nikclayton/android-squeezer#616]
The new version 2 is looking nice. But I went back to the previous version.
Reason is the tiles makes it hard to select files when browsing folders or favorites.
In the tiled view there is only room for the beginning of the names and that makes it hard to know which file or favorite is which.
eg. BBC radio 4 and BBC radio 4 extra looks the same is the tile view.
Also when entering a a folder with mp3:s, there is only room for the beginning of the file names which makes it impossible to select a specific track.

So it would be nice to be able to choose tiled mode or list mode in the user interface.
The favorites I can rename, but renaming all the files is to cumbersome.
So either a global setting where to choose tiled or list, or always list mode when browsing in the music folders.

**Comment by kaaholst** [comment]
To get the list view, please select Settings from the home screen, then select Screen and Small Artwork.
Hope this helps, and thanks for the feedback.

**Comment by bitwit42** [comment]
Thanks, worked fine. 
I missed finding that setting.

**Comment by HButler63** [comment]
Sorry, I think I am missing something, my settings only contain "Fade in", "Automatic connection", "Third party integration" etc., but no option related to the screen or artwork... Am I looking at the wrong settings somehow? I'd appreciate any help... Thanks.

**Comment by HButler63** [comment]
Sorry again, I found it, I somehow managed to miss the large "Settings" button :(
