### ISSUE TITLE
new v2 fails to find lms at 192.168.0.21:9393

### ISSUE THREAD

**Issue by xpseudonym** [nikclayton/android-squeezer#617]
New v2 fails to find lms at 192.168.0.21:9393

Upated yesteday and new app failed  - so reverted to backup of v1.5

I guess it's something to do with change to CometD protocol and custom port?

And, thank you for the stunning app!

**Comment by kaaholst** [comment]
The CometD protocol use the http-port to connect. That is the same address you would use to connect from a browser (on the phone or from another device). The old version uses the CLI-protocol which uses the CLI-port. Both ports can be found in settings in the server's web-interface.
You cannot use the same port for Squeezer v.1.5 and v2.
But Squeezer v2 is supposed to automatic discover servers on the local network including the port.

Why that doesn't work I don't know.

- What is the result of running a scan for servers from Squeezer?
- Can you connect to the scan result from the browser on the same device you run Squeezer?

**Comment by xpseudonym** [comment]
Strange; G Play offered the update again (no surprise) and it's connected without issue - I was offered the rescan/ connect page innitially, but simply tapping the 'connect' button connected to the (correctly) discovered default. Hmm...

**Comment by xpseudonym** [comment]
PS
big squares good :)
I like rounded edges to my squares, but think flat squares more contemporary

**Comment by kaaholst** [comment]
To switch big and small artwork please select settings from the main screen then select screen and small/big artwork.
About the icons some of them are embedded in the app, and some come fro the server. I tried to change the embedded ones, but didn't think it looked good blended in with those of the server. Something like the picture below.
If you use spotty it's an example of icons without the background with the rounded corners. (those are all from the server).
![image](https://user-images.githubusercontent.com/428304/75099816-684d3f80-55c6-11ea-8651-31bf5bb41638.png)

**Comment by ArnaudD-FR** [comment]
> The CometD protocol use the http-port to connect. That is the same address you would use to connect from a browser (on the phone or from another device). The old version uses the CLI-protocol which uses the CLI-port. Both ports can be found in settings in the server's web-interface.
> You cannot use the same port for Squeezer v.1.5 and v2.
> But Squeezer v2 is supposed to automatic discover servers on the local network including the port.
> 
> Why that doesn't work I don't know.
> 
>     * What is the result of running a scan for servers from Squeezer?
> 
>     * Can you connect to the scan result from the browser on the same device you run Squeezer?

LMS is hosted by my synology and http port used to connect is 9002. But the Squeezer V2 only propose port 9000... I believe the port discovery mechanism is not working.

Manually setting port to 9002 make squeezer V2 working fine

**Comment by kaaholst** [comment]
We had no issues about port discovery for about a year, so it seems to work.

I'm closing this issue. The issue tracker has moved, so please open a new issue on [https://github.com/kaaholst/android-squeezer/issues](https://github.com/kaaholst/android-squeezer/issues), if you encounter new issues.

Thanks for the feedback.
