### ISSUE TITLE
Thoughts about version 2 changes to the UI

### ISSUE THREAD

**Issue by elperepat** [nikclayton/android-squeezer#618]
Hi!

I first want to say thank you for the great app! It allows me to continue to use my LMS server and I really appreciate it!

Now to the comments about the 2.0 version:

I'm not really fond of the new big icons UI. I preferred the list UI you had before. Too much scrolling with the new one. I saw a lot more at a glance and it was easier to navigate in the menus before.

I'm not really sure why there's an overlay popup when I play or pause or skip using the buttons in the playlist view. It doesn't help me understand what is going on. The icons already changed from play to pause when I clicked it and the title changed when I pressed skip. The popup is more an annoyance to me than anything.

Otherwise, great app and again thank you for the time you spend keeping it alive and improving it.

Patrick

**Comment by HButler63** [comment]
I fully agree; I am very grateful for Squeezer since it allows me to control my beloved Squeezebox (without ads!). Thanks for the great work!

When seeing the new big icons, the first thing I tried was to find the setting to switch to the old "list" view (which wasn't there). Now, the space for the album name below each album is way too small to show the full name. This is quite annoying if many albums start with the same words ("Nice mix #1", "Nice mix #2", etc, where only "Nice mix" is shown below each of your 10 albums). I miss the nice overview of the previous version!

Is there any chance of adding an option to return to the previous list layout?

Thanks again for the great app, I hope it will be with us for a long time to come!

Hans.

**Comment by kaaholst** [comment]
Thanks for the feedback.

To get the list view, please select Settings from the home screen, then select Screen and Small Artwork.

About the messages about song changes and playing state, I agree they are not useful when in the Now Playing screen. I will see if I can detect such messages and ignore them while in the Now Playing screen.

Also the setting to switch between small and big icons is to difficult to find, so I will create a shortcut for that.

**Comment by elperepat** [comment]
Good! I thought all settings were in the 3-dot menu up right. I'm now back in list view.

However, I could use an even more compact list view. The icons are still a bit too large and the text is not centered vertically for each item and font is rather large. Reducing icon size by 25% would be a great size (even 50% if it's still usable). Right now I can see 8 items at once on my screen. 12 or more would be better in my opinion. It's the same once I get to the artist/album list. I'd prefer to see more artists/album at once on the screen.

Thanks!

Patrick

**Comment by justsomebody42** [comment]
Wow. I fell for the same "issue", thinking that the big settings icon was referring to the player settings... Glad I found this! Thanks.

Another thing I'm missing is the old search. It was possible to insert a search term and then immediately get the results for all different categories like "album", "artist" and so on.
Now I have to select the category first, which is bad, when I expect results from different categories.
What's worse is, that the possibility to search for genres seems to be gone (or maybe I'm just unable to find it...)
Is there a way to go back to the old search behaviour?
I even tried to clone the repository and build the 1.5.4 by myself, without any luck so far...

Anyway, thanks a lot for all the effort that's going into this!
Don't get me wrong, when I'm only complaining :D 
This is one of my most used apps on the phone!!

**Comment by justsomebody42** [comment]
And one additional thought: I really loved the big album covers in the search result, while having the very compact menu list.
Now it seems that I can either have big icons in the menu AND the album list/result or small menu list AND small album icons... :(

**Comment by HButler63** [comment]
Thanks for the hint, this solved it for me! Again I want to stress my appreciation for all your efforts, keep it up!

**Comment by kaaholst** [comment]
@justsomebody42 
If you choose search from the main screen rather than from My Music i think you will find it's more like the old behaviour. I don't have search for genres either.
The search functionality is now controlled by the server. Maybe it can be customized, e.g. via a plugin.
Bringing back the old behaviour with the new protocol will be difficult,. but I'll see what I can do.

**Comment by lim-on-air** [comment]
Hi,
good to have a freshly rebuild version of squeezer.
I agree for the big icons (setting difficult to find, not possible to have small menu icons and big album covers...)

Another functionnality I can't find is the possibility to organize the playlist (move up or down the tracks). Where is it ?

**Comment by charon6666** [comment]
Hello, sorry for my english, I'm french.
Why not possible to see in "genres" the album cover diaporama like the past version ? This is only possible when i choose "album" and here i find all my album. But not very simple to find a specific album.

I dislike the list. And why when  I enter to a "genre" like Jazz, we find a short list of artists and at the end the possibility to see all album ? Why not have directly all album seing ?


I like using Sqeezer in my system, for his simplicity, and with this new version, I find it more complicate.

C

**Comment by justsomebody42** [comment]
@kaaholst Thanks for looking into this!
Is it now impossible to download files to the phone? Or am I just to stupid to find it?
All a bit confusing...
Would it be possible to provide an apk for the previous version somewhere? :)
Still no luck with compiling it on my own... :(

**Comment by justsomebody42** [comment]
Thanks a lot for addressing the layout settings so quickly!!

**Comment by charon6666** [comment]
nobody for explain me ?

Charon

**Comment by kaaholst** [comment]
@charon6666 I've created a new issue for the genres navigaton #632

**Comment by charon6666** [comment]
@kaaholst thank you I go red that.

Charon

**Comment by nilskp** [comment]
_Really_ not a fan of the smaller cover, less than full width, in 2.1.0. Much waste of screen real estate.

![Screenshot_20200503-164055](https://user-images.githubusercontent.com/74843/80926457-098e0a00-8d5d-11ea-9800-432f570c3e1c.jpg)

**Comment by kaaholst** [comment]
You are quite right. The new layout takes care that all buttons are visible on all form factors. It does appear however that we should optimize for better use of white space, at least for the now playing screen. I will see what I can do for future releases.

**Comment by nilskp** [comment]
If possible, perhaps have a setting for "Always maximize cover art", to ensure full width. This can be disabled by default, but if it's a setting, it might be easier to implement, as it gives the user a little wiggle room?

**Comment by kaaholst** [comment]
These are either fixed or tracked by individual issues, so closing this.
@lim-on-air The possibility to organize the playlist is tracked #631 which I'm happy to say is coming in the next version.
