### ISSUE TITLE
Spotify FF/Rew

### ISSUE THREAD

**Issue by joesea7** [nikclayton/android-squeezer#619]
Thanks for v2. Especially appreciate getting Spotify search working. Hugely valuable. Well done.

Issue: The slider for fast forward/rewind resets to the beginning of the song

**Comment by kaaholst** [comment]
Hmm.. I assume you're using Spotty?
Dragging the current time forward and backwards works as expected, and skip next and previous song also works.
Could this be a server issue?
Does it work from another  controller or the server's web-interface?

**Comment by joesea7** [comment]
Yes, Spotty.  Next and previous song worked, just not the slider. I was also noticing that for mp3 songs I have stored locally (not streamed via a service) the slider was working in odd chunks.

I will experiment and get back to you with more info.

Thanks.

**Comment by joesea7** [comment]
It seems to be something with Spotty and my server. Web interface doesn't do anything and the slider on Spotify Connect just resets to the beginning of the song.

**Comment by kaaholst** [comment]
It seems this is an issue on your server a or plugin on the server. I'm afraid I can't offer much help about that. I suggest you ask a question on forums.slimdevices.com, maybe they can help.
