### ISSUE TITLE
After update to v2.0.0 the LMS port is not detected correctly

### ISSUE THREAD

**Issue by fri-sch** [nikclayton/android-squeezer#620]
The old version was successfully detecting and connecting to the local server at `servername:9000`. Now after the update, the detection still detects port 9000, but connection only works after manually switching to port 9002.

**Comment by kaaholst** [comment]
The new version connects via the CometD protocol which uses the servers HTTP-port. The old version used the CLI protocol which uses the CLI-port. You cannot use the same port for the new and old version of Squeezer.
Squeezer detects the servers on the local network, which you can select from a dropdown list in the connect screen.
If for some reason your server can't connect or you need some special setting, I have provided the possibility to manually enter the server address and port. This is selected by choosing "Manually enter address" from the dropdown. If no servers are detected this will be the only option.
If manual address is selected we don't detect address or port. If no port is entered (i.e. the number after the colon), then Squeezer attempts port 9000.

This was a long explanation, but I hope it makes sense.

**Comment by syphr42** [comment]
I'm having a similar problem after updating to v2 of the app. I am unable to get Squeezer (Android) to connect to my local server. However, I can connect to it via a web browser on the same device where the app is installed. 

I have the server running on port 80 and before I saw this I was trying to connect with no port number. However, if I specify port 80, it still fails to connect.

The only information I get back is "Connection failed." Is there any logging I can check in the app?

**Comment by syphr42** [comment]
My issue seems different so I opened issue #624 with more information.

**Comment by fri-sch** [comment]
> The new version connects via the CometD protocol which uses the servers HTTP-port. The old version used the CLI protocol which uses the CLI-port. You cannot use the same port for the new and old version of Squeezer.
> Squeezer detects the servers on the local network, which you can select from a dropdown list in the connect screen.
> If for some reason your server can't connect or you need some special setting, I have provided the possibility to manually enter the server address and port. This is selected by choosing "Manually enter address" from the dropdown. If no servers are detected this will be the only option.
> If manual address is selected we don't detect address or port. If no port is entered (i.e. the number after the colon), then Squeezer attempts port 9000.
> 
> This was a long explanation, but I hope it makes sense.

Thanks for explaining! If I understand this correctly then my issue is that I don't have a dropdown menu to choose between "Manually enter address" and the auto detection. After the update to v2, I get the "Rescan" button and next to it it says "Manually enter address", but without any option to select the automatic detection. That's probably the reason why I was confused, that I need to adjust the port manually.

**Comment by kaaholst** [comment]
Yes, your issue is that your server is not detected. I don't know why that is.
