### ISSUE TITLE
2.0 doesn't have the download option

### ISSUE THREAD

**Issue by howlett** [nikclayton/android-squeezer#621]
We were using the download option to sync music to our phones but it appears that 2.0 doesn't have this option.  Is this feature lost, is this a bug, or am I just not seeing where it has moved?

**Comment by phiber2k4** [comment]
I have the same issue - definitely love the UI overhaul, but miss the download functionality.

**Comment by darylfoster** [comment]
I was also using the download option to quickly move music to my phone. Is there a way to request that this feature be added back?

**Comment by hormey** [comment]
Thank you for the awesome app - but we miss the download functionality as well.

**Comment by Korittky** [comment]
The missing download option hurts me and is not compensated by the 2.x improvements. It would me mega nice if anyone could re-enable the functionality.

**Comment by kaaholst** [comment]
Work on restoring download functionality is done in the download branch.

Download isn't really a supported feature of the server protocol, and there are also issues no the Android side, in particular when downloading multiple files. 

It does seem however that this is a high requested feature, so I am doing what I can to bring it back.

**Comment by hormey** [comment]
That sounds nice. Thank you!

**Comment by Snowman-25** [comment]
Yes, please add back the download option. Had to revert to the latest 1.5 to pump my new phone full of music

**Comment by attractedtofire** [comment]
Oh…I thought there might be an open issue already. Having the download feature back would indeed be much appreciated!! Thank you for your great work. :)

**Comment by realreform** [comment]
Ditto, on the download feature please. Great app.

**Comment by aortez** [comment]
Looks like this feature has landed?  Am I on track here?  If so, then thanks! :bow: :bow:, this is such a handy feature!

**Comment by attractedtofire** [comment]
Yes and it works great. Thank you very much for managing to accommodate this!! :+1: :)

**Comment by realreform** [comment]
Excellent

**Comment by kaaholst** [comment]
Download is available in 2.2.0 which is on Google play now, so closing this.
Thanks for the feedback.
