### ISSUE TITLE
Wired network connection problem - solved

### ISSUE THREAD

**Issue by productiveNetwork** [nikclayton/android-squeezer#622]
Hi, it seemed that the 2.0.0 version doesn't connect with wired connection.
![SmartSelect_20200222-220626_Squeezer](https://user-images.githubusercontent.com/61363740/75100921-cd0f9680-55d4-11ea-9742-5afba8ac4ca6.jpg)
But, I'm really sorry! I was connecting the old 9000 port, squeezer 2.0 is connecting on port 9002 without issues.. Great work guys. thanks!

**Comment by kaaholst** [comment]
Glad you got it working.
It seems that server discovery should be possible on wired network. I'll see what I can do.

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/623](https://github.com/kaaholst/android-squeezer/issues/623)

Please use that for future comments.
