### ISSUE TITLE
Cannot connect to LMS after update to 2.0.0

### ISSUE THREAD

**Issue by syphr42** [nikclayton/android-squeezer#624]
After the Squeezer upgrade on Android, I am no longer able to connect to LMS running on my network. However, I am able to connect to LMS using the web browser on the same device where Squeezer is installed.

I'm using Android 10 on a Pixel 3 with Squeezer 2.0.0. LMS is running on port 9000, but it sits behind a reverse proxy (Traefik) which is listening on port 80. LMS is version 7.9.1.

In Chrome or Firefox, `http://lms-host:80` loads the web UI correctly and control of players works as expected.

Using tcpdump on the server, I see the following when I try to connect from Squeezer:

Request
```
POST /cometd HTTP/1.1
Content-Type: text/json;charset=UTF-8
Content-Length: 188
User-Agent: Squeezer-squeezer/2.0.0

[{"ext":{"rev":"2.0.0","uuid":"1ccfd666187a46bdac274981175169a8","mac":"redacted"},"supportedConnectionTypes":["streaming"],"channel":"/meta/handshake","id":"33","version":"1.0"}]
```

Response
```
HTTP/1.1 400 Bad Request: missing required Host header
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Request: missing required Host header
```

If I send the same request via Postman from a different device, I get the following body with an HTTP 200:
```
[{"supportedConnectionTypes":["long-polling","streaming"],"successful":true,"channel":"/meta/handshake","advice":{"reconnect":"retry","timeout":60000,"interval":0},"clientId":"17009665","version":"1.0"}]
```

**Comment by syphr42** [comment]
Watching the Postman request via tcpdump shows that it is adding the `Host` header even though I don't set it explicitly. It seems like the request from Squeezer is missing the `Host` header as the message implies.

**Comment by syphr42** [comment]
It seems like the `Host` header is a required part of HTTP 1.1 according to the spec (https://tools.ietf.org/html/rfc7230#section-5.4).

**Comment by kaaholst** [comment]
Thanks for the detailed issue description.

You are right, this is a different issue. I think you have provided enough information, so I can prepare a fix for this. I am however not able to test it, as I don't run a proxy. So I will be grateful if you will assist in testing this, once I get a fix ready.

**Comment by syphr42** [comment]
Sure, I'm happy to help. Thanks for the quick response!

**Comment by kaaholst** [comment]
Please try this [apk](https://drive.google.com/open?id=1ZhrAs3bjmuiVL0axfcXxLPj9pk2TgsV-), which sets the Host header.
To install open the link on your phone.

**Comment by syphr42** [comment]
I tested the apk and there is definite improvement. I see the `Host` header being sent. When I hit "Connect" in Squeezer, I see my player show up and even the last played song for a few moments and then it exits back to the connection screen.

I've looked at the tcpdump briefly and I don't see any errors. All the HTTP requests look like they are getting a 200 back, so I'm not sure why it is exiting. I probably won't be able to look at this again until the weekend, but if you have any ideas for something to try or some data to gather for you to debug, let me know.

**Comment by syphr42** [comment]
I finally got back to this. I removed the apk you provided and started over installing it and testing with my server and now it is working exactly as expected. I'm not sure what happened when I tried it the first time, but this fix looks good with my proxy.

**Comment by kaaholst** [comment]
Oh that's good to hear, I was afraid this one could not be solved.

I'm happy you got it working, and thanks for your help in sorting this out.
