### ISSUE TITLE
Favourites not updated after deletion

### ISSUE THREAD

**Issue by cybernoid** [nikclayton/android-squeezer#625]
Hi,

there's a small bug on the favourites page: when I delete a favourite via it's 3-dot context menu, the deletion obviously happens but the screen is not redrawn. The deleted favourite is still shown, but points to the next favourite now. Leaving and re-entering the favourites page renders it correctly without the deleted favourite, so I think it's really simply the redrawing that's missing.

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/626](https://github.com/kaaholst/android-squeezer/issues/626)

Please use that for future comments.
