### ISSUE TITLE
Playlist as favourite does not work

### ISSUE THREAD

**Issue by cybernoid** [nikclayton/android-squeezer#626]
Hi,

another issue with the 2.0 app's favourite screen: I added a playlist as favourite and it shows up like it should, but trying to play it only results in the player stopping and "unknown title" appearing in the status bar. Also adding its content to the current playback via the 3-dot menu and so on does not work, as if the playlist was empty (but it definitely wasn't when I added it).

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/627](https://github.com/kaaholst/android-squeezer/issues/627)

Please use that for future comments.
