### ISSUE TITLE
Request: volume buttons

### ISSUE THREAD

**Issue by echable9999** [nikclayton/android-squeezer#628]
Could you please include an option for now playing screen to have visible ÷ and + volume buttons ? 

There is room under progress bar / over rwd/ffwd buttons. 

Great for using e.g. with a tablet sitting on a stand, where using device physical buttons could eg make the device unstable. 

Thank you for considering this.

**Comment by kaaholst** [comment]
I agree that is convenient. t will come in a later version, in the meantime, you can select the 3-dot menu in the top right corner, and then select Change volume.
