### ISSUE TITLE
Request: 'Always On' display for phones that support it

### ISSUE THREAD

**Issue by Toonuser** [nikclayton/android-squeezer#629]
On phones that have 'always on' display, it would be brilliant to be able to see currently playing info, without the need to touch the phone.

Btw, I've just started using V2. Great work so far, and the only bug I've found is that most of the time it doesn't automatically reconnect when opening it up.

**Comment by kaaholst** [comment]
That is a good idea. This will come in a later version.

**Comment by Toonuser** [comment]
OK great, thanks!

**Comment by kaaholst** [comment]
Note to self:
https://developer.android.com/training/monitoring-device-state/battery-monitoring
https://developer.android.com/training/scheduling/wakelock

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/630](https://github.com/kaaholst/android-squeezer/issues/630)

Please use that for future comments.
