### ISSUE TITLE
Genre navigation under CometD

### ISSUE THREAD

**Issue by kaaholst** [nikclayton/android-squeezer#632]
The genre functionality under CometD is:
_Music -> Genres -> Artists -> Albums_
additionally there is an All Albums at the bottom, which is sorted according to the Album Sort Method, which is configured under settings.

Previously we had:
_Music -> Genres -> Albums_
and via the context menu for each genre it could be chosen to browse by Albums, Songs or Artists.

As with anything under CometD Squeezer simply requests a menu from LMS and display the options. This means changes to the functionality should be done on the server.
In this case however, it may be possible to change how we browse items as indicated [here](http://wiki.slimdevices.com/index.php/SBS_SqueezePlay_interface#SqueezeCenter_command_implementation). I am investigating this.

In the meantime it is possible to create an additional browse mode, for a specific list, e.g. like this:
![image](https://user-images.githubusercontent.com/428304/77523496-1aa64a00-6e86-11ea-99a2-0056b0082ad5.png)

It will then turn up in the Music Menu:
![image](https://user-images.githubusercontent.com/428304/77524979-930e0a80-6e88-11ea-8895-3d1d5ad4a1ab.png)

The Album order can be set from Squeezer via
Home -> Settings -> Advanced -> Albums Sort Method
![image](https://user-images.githubusercontent.com/428304/77482414-22360680-6e26-11ea-920c-5c7a8a780fa3.png)

**Comment by justsomebody42** [comment]
You made my day!
I didn't know about the additional browse mode before and clearly, moving to CometD means I should pay more attention to the server settings/functionality.
Thanks for noticing this!! 😍

**Comment by charon6666** [comment]
if it's possible to have Genre-> Albums it's great.
I see that today, I go to my Pop-Rock's genre, I have the Artist list, at the bottom select all albums, the next page open to the new all list albums with cover, I scroll it and miracle the list album become an album covers slideshow. But ONLY for this genre, another I stay with the albums list and small cover. i hope we can in the next time to go directly to the ancient slideshow from the genre selected and don't have the list album.

I hope to be clear sorry for my english. If needed to be understand I can send somes screenshots.

Charon

**Comment by kaaholst** [comment]
Copied from https://groups.google.com/forum/#!forum/android-squeezer:

Genre Navigation Request

Previous versions:
My Music --> Genres --> (Select Genre) --> Display all albums matching genre, sorted according to album name.

New Version:
My Music --> Genres --> (Select Genre) --> Display of all artists with albums matching genre, sorted by artist

To get back to a list of albums matching the selected genre using the new version I have to scroll to the end of the artist list to find an "All Albums" option.  This then gives me a list of albums matching the selected genre, but still sorted by artist.  Can this please be reverted back to sorted by album rather than artist (the previous screen was sorted by artist; this is an album list not an artist list).

Further, can the "All Albums" link please be moved to the TOP of the artist list?  This isn't too much of a problem with esoteric genres but, for example, when selecting Rock, I am presented with a huge list of artists (my collection has over 2,000 individual album artists) and need to scroll to the bottom (and wait for it to populate) before I can click "All Albums".  Personally I use the album artwork to assist in album selection so clicking on each artist one-by-one to find a specific album is not practical; scrolling a list of albums  matching the selected genre, along with their  corresponding artwork, works so much better for me.

Thanks greatly!

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/633](https://github.com/kaaholst/android-squeezer/issues/633)

Please use that for future comments.
