### ISSUE TITLE
Customize which items are displayed/hidden from the home menu

### ISSUE THREAD

**Issue by kaaholst** [nikclayton/android-squeezer#636]
Copied from a Google Play review:

Fast in connection but not very configurable and full of unnecessary categories. Can't customize the main menus with what you want? Extra, my app, gallery .. Can they be removed? Same thing inside MY MUSIC: can only the desired categories be displayed?

**Comment by Jorgeno** [comment]
Totally agree, this feature would be great!

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/637](https://github.com/kaaholst/android-squeezer/issues/637)

Please use that for future comments.
