### ISSUE TITLE
New search bar

### ISSUE THREAD

**Issue by w4nn3r** [nikclayton/android-squeezer#640]
Hi,
first of all, let me say how great the new version of the app is, I love it. I especially love the global search bar, but I would like to suggest 2 improvements to it :
- when you tap the search icon, it would be great if the focus was on the text field, it would save some time
- I would like it to be possible to choose what music collection the search operates from. Currently, when you make a search, it then displays 2 choices : "My Music" and "Google Music", and then in "Google Music" I choose "All Access" and then "Tracks". I would like, as an option, to directly display the "Tracks" results, to save some time. But you can also make it possible to choose the "Artists" results in priority, or the Local Music Source, or whatever the user prefers...

Thanks in advance :)

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/641](https://github.com/kaaholst/android-squeezer/issues/641)

Please use that for future comments.
