### ISSUE TITLE
auto-detection of server works but does not update address

### ISSUE THREAD

**Issue by sturgman** [nikclayton/android-squeezer#641]
Recently the IP address of my server changed. I auto detected the ip and squeezer reported my server by name. However it didn't update the ip address to the new server. Switching to manual insertion of ip and back populated  right address.

Android: 6.0.1
Squeezer: 2.1.0

**Comment by kaaholst** [comment]
Thanks for the feedback.
I will see if I can reproduce and fix this.

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/642](https://github.com/kaaholst/android-squeezer/issues/642)

Please use that for future comments.
