### ISSUE TITLE
balance control

### ISSUE THREAD

**Issue by droogi** [nikclayton/android-squeezer#647]
Is it possible to add a balance control similar to loudness control?
Maybe a mono button could be useful?

**Comment by kaaholst** [comment]
Thanks for the suggestion

I can't seem to find anything about balance in the documentation for the LMS communication protocol though. 

Do you have any player which supports balance?

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/648](https://github.com/kaaholst/android-squeezer/issues/648)

Please use that for future comments.
