### ISSUE TITLE
Request: Make 'Sleep' control easier to find - Add to top level menu ellipsis

### ISSUE THREAD

**Issue by diyfiddler** [nikclayton/android-squeezer#648]
Is it possible to move or duplicate the player 'Sleep' control directly into main menu (top right ellipsis)?
Currently this control is found in Menu>Players>Player-X>Sleep which is not the most obvious place to look.  This is a common function used in our house and the time when you want to use it is usually just after you have started to play something on the particular selected player that you are controlling. Therefore it would make a bit more sense to have the sleep control closer to the top of the menu options for that selected player, such as just above or below "Turn on/Turn off "Player-X"".  
The ability to sleep other players could still be under the existing menu location as it currently is.
Just a thought. Thanks anyway for a great app!

**Comment by kaaholst** [comment]
Thanks for the suggestion.

I will add "Sleep" item to the options menu (the 3-dot menu in the top right corner) in the next version.

Incidently Sleep is currently accessible also via Settings from the main menu.

**Comment by kaaholst** [comment]
This is available in 2.2.0 so closing this.
Thanks for the feedback
