### ISSUE TITLE
Request: Please force LTR interface

### ISSUE THREAD

**Issue by beytarj** [nikclayton/android-squeezer#649]
Hi,
My phone have RTL interface, but the app interface is not compatible with this.
Please force LTR interface.

Great app!

**Comment by kaaholst** [comment]
Hi and thanks for the suggestion,

I decided to try to implement support for RTL interface instead.

If you like to try it out it's available (along with other updates) here:
[https://play.google.com/apps/testing/uk.org.ngo.squeezer](https://play.google.com/apps/testing/uk.org.ngo.squeezer)

You can opt out of the testing programme at any time, instruction are at the above link.

**Comment by kaaholst** [comment]
RTL interface is supported in 2.2.0 so closing this
Thanks for the suggestion.
