### ISSUE TITLE
Raspberry Pi SqueezeBox controller

### ISSUE THREAD

**Issue by lubelg** [nikclayton/android-squeezer#650]
I know this might be sort of off-topic but I'm not sure how else to ask:

I run piCorePlayer on a piZeroW, with an Amp hat as my bathroom music source. At the moment, I control it via my phone with Squeezer - which is excellent BTW,  but I'd rather not have my phone as the controller, I'd rather waterproof a dedicated Raspberry Pi, with LCD touch screen, using Squeezer. How difficult would it be to create a Pi fork of Squeezer? If that's too difficult, might there be an Android emulator solution that could work (technically and performance). I'd have a go at it myself if I was any shakes as a coder, unfortunately, I'm not. Alternatively, are there other Pi capable products that could do a Squeezer-like job?

Many thanks

**Comment by lord-aerion** [comment]
Why not simply use the Jivelite app that comes with pCP?

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/651](https://github.com/kaaholst/android-squeezer/issues/651)

Please use that for future comments.
