### ISSUE TITLE
Make Squeezer resizable

### ISSUE THREAD

**Issue by alexanderadam** [nikclayton/android-squeezer#651]
I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing for Android applications](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and the application is always nearly squarish:

![Screenshot of Squeezer on Samsung DeX](https://user-images.githubusercontent.com/372620/88280388-06644380-cce6-11ea-8964-65a6499f17ef.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.
**PPS:** I'm not sure whether this is relevant but [this](https://codeberg.org/gitnex/GitNex/pulls/601/files) is how GitNex fixed the issue and [this](https://github.com/TobiGr/NewPipe/commit/ea486e769ff9728c4e5d7dac6028587c39476fa9) is how NewPipe fixed it. Both are now also resizable with dragging border and corners.

**Comment by kaaholst** [comment]
Hi,

Thanks for the detailed description and the links for how to enable and test it.

I have enabled Multi-Window Support in Squeezer, it is available here:
[https://play.google.com/apps/testing/uk.org.ngo.squeezer](https://play.google.com/apps/testing/uk.org.ngo.squeezer)

As I don't have a Samsung DeX, I was only able to test on an emulator as described in the app testing guide, so it would be greatly appreciated it you will help test this using the above link. You can leave the test programme at any time, instructions for leaving are on that page as well.

**Comment by alexanderadam** [comment]
Hi @kaaholst,

it's working percetly! Thank you so much!

How long will it roughly take to land in the stable version of Squeezer?

**Comment by kaaholst** [comment]
If there are no issues with the new version, I will publish it in a few days. Then Google usually needs some days to verify it. So with any luck it will be available on Google Play in a week or so.

**Comment by kaaholst** [comment]
Version 2.20 is released now, so closing this.
