### ISSUE TITLE
Request: Volume control of a player group

### ISSUE THREAD

**Issue by H34dl3ss** [nikclayton/android-squeezer#652]
Please add the possibility to control the volume of a player group.
I'm using a couple of synchronized players in one room. Once the volume is set for each player, I would like to control them
synchroneusly (all up / all down).

**Comment by CDrummond** [comment]
As a work-around you could use the 'Group Players' plugin. This allows yo to create a 'virtual' player that represents the sync group. With this method you don't need to keep syncing players - jsut select the group player.

**Comment by kaaholst** [comment]
Next version will support the LMS settings for Synchronize Volume and Power of a player group. These can set by a three-dot menu to the right of the group name. This will ensure all players in the group have the same volume and/or are all turned on or off.

If the volume of the player group is not synced by LMS, there will be a slider below the group name (above the players in the group), which will adjust the volume of all players in the group (all up / all down). The volume of each player in the group can then be controlled individually via the slider for that player.

**Comment by kaaholst** [comment]
This is available in Squeezer version 2.2.2, so closing this issue.
