### ISSUE TITLE
Feature Request: interactive Now Playing screen

### ISSUE THREAD

**Issue by lord-aerion** [nikclayton/android-squeezer#653]
I'm currently evaluating Squeezer as a possible replacement for Orange Squeeze, which is sadly not open source and therefore not on F-Droid, a real hindrance in my attempt to go as Google free as possible.

Squeezer looks pretty nice, but it's lacking a few features I've come to really appreciate in Orange Squeeze.

It would be great to have the artist name, album title, and song title on the Now Playing as clickable links.

If I want to listen to a different album by the artist I'm currently listening to, I need to either return to the home screen and browse my collection again, or click on the search icon and search for the same artist again.

In Orange Squeeze I can simply click on the artist name and be taken straight to all releases by that artist. The album and song title are also interactive in Orange Squeeze.

Other use cases are:
- listening to a random playlist, and you want to check out a given artist's other releases
- listening to a particular song and you want to see on which other releases in your collection that song also appears or discover songs with similar titles in your collection
- you've only added a single song of a given album to your playlist and want to go back to that album to add more songs to the playlist or even listen to the entire album.

All of these use cases currently require far too many steps, especially when you come back to the app after it's been closed by Android's memory manager, and the back button no longer takes you back to the previous screen.

**Comment by kaaholst** [comment]
Thanks for the suggestion,

What you are describing I think is already possible in Squeezer, albeit in a slightly different way. 

The 3-dot menu to right of the song of the Now Playing screen is for this functionality. Pressing it gives you the options you request plus others. E.g. for a track from your local music library, you can browse Track Artist, Album Artist, Genre, Year, Lyrcis, Song info, ...

All these options come from LMS. If a new version of LMS provides other options, they will be displayed in Squeezer automatically.

**Comment by lord-aerion** [comment]
Indeed it is possible this way, and I did find this.

The way it works in Orange Squeeze is a lot more convenient though as it only requires one single tap. In Squeezer it requires accessing the menu, then scrolling through the list to find the desired option, then tapping that. On landscape devices, like the Planet Computers series of devices, this list is limited to just 4 lines, making finding the desired option even more finicky.

I'd therefore still like to see the artist, album, and song title become interactive links, given that that information is already visible on the screen. It's always desirable to require the least amount of interaction for the most used elements.

Having the other options hidden away in the menu makes sense, especially if these are dynamically changed depending on what LMS makes available.

**Comment by kaaholst** [comment]
Ok, interactive song title, album and artist on the Now Playing screen con coexist with the three-dot options.

From your comments a understand that

- Album -> Tracks of album of currently playing song
- Artist -> Albums of artist of currently playing song.

What, if anything, should in your opinion happen when the title of currently playing song is pressed?

Note, to align expectations, interactive Now Playing items are possible only for tracks from your local music library, and the options are limited to what is documented in "The Logitech Media Server Command Line Interface", which can be found via the Web UI / help / documentation. The options in the 3-dot menu are managed by LMS.

**Comment by lord-aerion** [comment]
The way it works in Orange Squeeze is that when you tap on the song title it creates a search with the song title as the criterion.

You can then choose how you want to search for this song title in your libary: Artists, Albums, Songs, or Playlists.
Searching Songs, for example, is very useful to find other versions of this song that you may have in your library, e.g. remixes, live versions, edits, remasters. Or you can search Albums, to find all albums a song with that title appears on, e.g. cover versions by other bands.

Because I've got Spotty installed on my LMS I can also submit the search to Spotify instead.

The Artist and Album links work in a similar way, except that Artist takes you to that artist in your library, showing all releases by that artist. Album takes you to that album in your library, showing all the tracks on that album. And in both case Spotty provides a link to browse that artist or album on Spotify instead.

When you've just browsed, say, an artist, selected an album and are playing tracks from it, you can of course just tap the back button to go back to the album list for that artist, but this doesn't work when the app has been closed. In this case it's very convenient to be able to go straight to the album or track list simply by tapping the artist name or album title respectively, instead of going through the kebab menu, or browsing the library again from the main screen.

Please let me know if you'd like me to provide screenshots of how this looks in Orange Squeeze.

**Comment by kaaholst** [comment]
Thanks for the suggestions. I think it should be fairly straight forward to make this work, and as you say it's a convenient feature.

**Comment by kaaholst** [comment]
This will be available in the next version of Squeezer, which is in beta now.
You can opt in the beta here: [https://play.google.com/apps/testing/uk.org.ngo.squeezer](https://play.google.com/apps/testing/uk.org.ngo.squeezer).
You can opt out of beta any time.

**Comment by lord-aerion** [comment]
Great news! I'll sign up for the beta this weekend. Thanks!

Will the new version be made available on F-Droid again?

**Comment by kaaholst** [comment]
I'm currently looking into putting Squeezer on f-droid.
It look promising, so I hope it will be available soon.

**Comment by kaaholst** [comment]
This is available in Squeezer version 2.2.2, so closing this issue.

**Comment by lord-aerion** [comment]
Just to let you know, this is working as requested, awesome!! Thank you so much for implementing this request!!

My only minor follow-up request would be bigger fonts. There's a lot of empty space below the progress bar, yet the album title and band name are rather small and require precision tapping.

Very happy with this otherwise, one step closer to making Squeezer my default LMS app. A donation will be coming your way as soon as my finances pick up.
