### ISSUE TITLE
Feature Request: support for alternative scrobblers

### ISSUE THREAD

**Issue by lord-aerion** [nikclayton/android-squeezer#654]
Squeezer only has support for Last.fm

It would be great to have additional support for the following open source alternatives:

- [ListenBrainz](https://listenbrainz.org/) (part of MusicBrainz)
- [Libre.fm](https://libre.fm/)

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/655](https://github.com/kaaholst/android-squeezer/issues/655)

Please use that for future comments.
