### ISSUE TITLE
FeatureRequest: Use NFC to change Player

### ISSUE THREAD

**Issue by 3bs1** [nikclayton/android-squeezer#655]
Hi,

Great app, I like it a lot. After using it for some years already, an idea came to my mind.
It would be a great id you could place the tablet or mobile phone you use for remote controlling on a NFC tag e.g. when you are on the balcony and squeezer would choose "balcony" as the player to be controlled.
Going back to the living room with the tablet, you put it on the couch table, where another NFC tag is placed and it automatically would choose the player "livingroom" to be controlled.

Either a buildin function or some kind of integration with tasker (or similar app) woul be great.

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/656](https://github.com/kaaholst/android-squeezer/issues/656)

Please use that for future comments.
