### ISSUE TITLE
BUG: Download-Option falsely adds .mp3 to filenames

### ISSUE THREAD

**Issue by Snowman-25** [nikclayton/android-squeezer#656]
As stated in the title:
When downloading .wma or .wav-files, they will appear as .wma.mp3 and .wav.mp3 respectively. No conversion has been done, however. The files are still in their source-format

**Comment by wombatch** [comment]
The download appends mp3 this seems to be useless, it seems to do it for anything not mp3 or m4a. My library is all flac. Presumably libraries will already have the correct file type, why change anything in the name, just download it.

**Comment by kaaholst** [comment]
You are right this is an issue from Android 10 on newer. A new concept is introduced: Scoped Storage. In Scoped Storage we can only store files to the app-specific directory. This means that your media player will not be able to see it. Instead we have to insert it into a MediaStore collection using a ContentResolver. Unfortunately that renames the file. I don't why it does that, and I have not been able to fix it.

**Comment by kaaholst** [comment]
I have found a way to avoid Android adding .mp3 to the filename. It will be fixed in 2.2.1 which is in beta test now, and should be available on Google Play soon if you are not a beta tester.

**Comment by kaaholst** [comment]
This is fixed in Squeezer version 2.2.1 and newer, closing.
