### ISSUE TITLE
Wake-on-LAN - send WoL to the LMS server

### ISSUE THREAD

**Issue by kaaholst** [nikclayton/android-squeezer#657]
When starting Squeezer sends Wake-on-LAN
Enter MAC address for the server running the LMS.

**Comment by Jorgeno** [comment]
This would be great!

**Comment by kaaholst** [comment]
Wake-on-LAN will be in the next version of Squeezer, which is available in beta. To opt in press [here](https://play.google.com/apps/testing/uk.org.ngo.squeezer).
You can opt out any time.

**Comment by kaaholst** [comment]
This is available in Squeezer version 2.2.2, so closing this issue.
