### ISSUE TITLE
Volume Control widget on Home Screen

### ISSUE THREAD

**Issue by xpseudonym** [nikclayton/android-squeezer#660]
Squeezer is stunning!
The new(ish) volume control is stunning!
I would like - and others might too - access to the volume control from the Home Screen so I don't need to tap through to they Player Screen (and back again) to adgust the volume.
There seems (to me) to be room for a small speaker icon/ widget directly to the left of the play icon/ widget bottom right corner of the Home Screen (no text), see attached screen shots.
Thanks
![Screenshot_20201001-090736](https://user-images.githubusercontent.com/5032475/94785368-71598700-03c7-11eb-80ba-074525463572.png)
![Screenshot_20201001-090616](https://user-images.githubusercontent.com/5032475/94785408-7ddddf80-03c7-11eb-89d7-cc465992490f.png)

**Comment by kaaholst** [comment]
In the next version of Squeezer there will be a volume icon button in the bottom if the screen is wide enough.
This version is available in beta, which you can join [here](https://play.google.com/apps/testing/uk.org.ngo.squeezer).
You can opt out of the beta programme any time.

**Comment by kaaholst** [comment]
This is available in Squeezer version 2.2.2, so closing this issue.

**Comment by xpseudonym** [comment]
Thank you - that's great!
Morgan
