### ISSUE TITLE
First item in listing played in soundcloud app, no matter which item in listing is selected

### ISSUE THREAD

**Issue by vincebowdren** [nikclayton/android-squeezer#661]
Summary: When using Squeezer to control the SoundCloud app, it is not possible to select an item from a listing (e.g. of Likes, or Search results). Whichever item from the listing is selected - e.g. 2nd or 3rd or 4th - squeezer always selects and plays the listing's first item.
By contrast, if I use the Logitech Media Server web UI then I can select whichever item I want from the listing.

Versions:
- App: Squeezer 2.2.0
- OS: Android 8.0.0
- Hardware: Samsung Galaxy A3 (2017)
- Player: Squeezebox Touch

Steps to reproduce:
1. precondition: the SoundCloud app needs to be installed
2. in Squeezer, navigate:
   - My Apps
   - SoundCloud
   - Search
3. Enter a search term, e.g. in my example "DJ food"; the search results are shown, with a number of different items listed
4. Pick any one of the items except the 1st - in my example, I picked the 2nd - open the hamburger menu, and select Play (see attached screenshot 1)
Expected result: the selected item is played
Actual result: the 1st item from the search results is played (screenshot 2)

[Squeezer_SoundCloud_FirstItem_Screenshots.zip](https://github.com/nikclayton/android-squeezer/files/5312763/Squeezer_SoundCloud_FirstItem_Screenshots.zip)

Comparison steps using the Logitech Media Server web UI:
1. in the web ui, navigate: 
   - Home
   - My Apps
   - SoundCloud
   - Search
2. Enter a search term; the search results are shown, with multiple items listed
3. Pick any one of the items except the 1st - in my example, I picked the 6th - and press the play button (screenshot 3)
Expected result: the selected item is played
Actual result: the selected item is played (screenshot 4)

PS Does this advice still apply? https://github.com/nikclayton/android-squeezer/wiki/Apps-support-in-Squeezer

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/662](https://github.com/kaaholst/android-squeezer/issues/662)

Please use that for future comments.
