### ISSUE TITLE
Volume adjustment/Crossfade setting

### ISSUE THREAD

**Issue by blscorp** [nikclayton/android-squeezer#662]
Running on Samsung Galaxy S9, Android 10. 

Since last update (2.2.0), the buttons for setting Volume Adjustment and Crossfade options have lost functionality; all buttons light when touched rather than switching between the selected option, and then are stuck on and can't be deselected.  See attached screenshots
![Screenshot_20201003-134200_Squeezer](https://user-images.githubusercontent.com/72315638/94998476-08693f00-0580-11eb-822a-c35a82fbbc4c.jpg)
![Screenshot_20201003-134447_Squeezer](https://user-images.githubusercontent.com/72315638/94998483-16b75b00-0580-11eb-9f80-7924fd8d5d34.jpg)

**Comment by kaaholst** [comment]
You are right, it is is a bug. This will be fixed in the release.
Sorry for the inconvenience, and thanks for taking the time to report this.

Note:
When an option is selected, the selection is still saved on LMS. even if the display doesn't reflect it.

**Comment by blscorp** [comment]
Oh, that's good to know.  Thank you for responding so quickly!
And thanks for the great app.

While I have you: two of my favorite features on the old Squeeze Control
app that aged out of Android, were 1) the ability to reorder playlists by
simply dragging tracks up and down in the playlist view, and 2) the ability
to automatically mute or cut player volume when you get an incoming phone
call.

Any interest in adding to Squeezer?

Thank you again

Ben

**Comment by kaaholst** [comment]
Reorder playlist is also coming in the next release, tracked by #631.

There is also a request for mute on incoming call at #46. Please comment or vote on that issue, if you are interested in this feature.

**Comment by kaaholst** [comment]
This is fixed in Squeezer version 2.2.1 and newer, closing.

**Comment by blscorp** [comment]
I noticed!  Well done and thanks.
