### ISSUE TITLE
Option for larger bar in landscape mode 

### ISSUE THREAD

**Issue by jwoodard80** [nikclayton/android-squeezer#663]
Literally have used every client on Android and i keep coming back to squeezer! Thank you all for the time and work you put in!

I have a 8in tablet in my main hall that serves as the central controller for our house. It stays in landscape all day. It would be nice to have an option to increase the height of the bar along with larger control buttons to make the interface a little easier to navigate and look more proportional.

I would like to see this as just an option as others might not like it. :-) 

![Screenshot_20201010-222310_Squeezer](https://user-images.githubusercontent.com/10240627/95669603-27e80500-0b48-11eb-9b8d-caff674045b3.jpg)

**Comment by lord-aerion** [comment]
This would also be useful on landscape devices such as the Planet Computer series of devices.

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/664](https://github.com/kaaholst/android-squeezer/issues/664)

Please use that for future comments.
