### ISSUE TITLE
Feature Request: Background Volume Control

### ISSUE THREAD

**Issue by daniel1v** [nikclayton/android-squeezer#665]
It would be a nice addition to allow changing player volume with the app running only in background. 

I think therefore the app has to tell the system, that it is streaming audio in the background, to get control over the volume keys. I dont know the API for this, but some existing apps have this feature. 

Spotify for example has this integrated, when using it to control Spotify Connect devices. Also Chromecast streaming supports this feature.

**Comment by kaaholst** [comment]
This should be possible using a MediaSession which is available from Android 5.0. 

Below is some technical notes on how to implement it:
private MediaSessionCompat mediaSession = new MediaSessionCompat(this, "PlayerService");
mediaSession.setFlags(MediaSessionCompat.FLAG_HANDLES_MEDIA_BUTTONS | MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS);
mediaSession.setPlaybackState(new PlaybackStateCompat.Builder().setState(PlaybackStateCompat.STATE_PLAYING, 0, 0).build());

VolumeProviderCompat myVolumeProvider = new VolumeProviderCompat(VolumeProviderCompat.VOLUME_CONTROL_RELATIVE, 50) {
    @Override
    public void onAdjustVolume(int direction) {
        /*
        -1 -- volume down
        1 -- volume up
        0 -- volume button released
         */
    }
};

mediaSession.setPlaybackToRemote(myVolumeProvider);
mediaSession.setActive(true);

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/666](https://github.com/kaaholst/android-squeezer/issues/666)

Please use that for future comments.
