### ISSUE TITLE
Feature Request: Party/Jukebox Mode

### ISSUE THREAD

**Issue by bennigecko** [nikclayton/android-squeezer#666]
It would be great if it were possible to enable a Jukebox Mode in the app which only gives the option to browse the library and add tracks to the end of the playlist. I managed to set my server in "non destructive" mode so there is a dialog asking what you want to do when selecting a track instead of instantly playing it. However, I can still do so if I want to deliberately. In order to keep people at a party from switching songs every few minutes in jukebox mode it should only be possible to add songs to the end of the playlist.

**Comment by kaaholst** [comment]
As options are controlled by the Logitech Media Server I'm not sure if this is possible. 

However Jukebox Mode is a good idea, so your request is noted. I will post back here if there is any progress on this issue.

**Comment by bennigecko** [comment]
Thanks a lot for considering it!

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/667](https://github.com/kaaholst/android-squeezer/issues/667)

Please use that for future comments.
