### ISSUE TITLE
New Feature Request: modify list display to One Line Per Item

### ISSUE THREAD

**Issue by gstalnaker** [nikclayton/android-squeezer#667]
In other words, provide option to NOT display full track title and artist for each item in any action that results in a list of items & just display item on a single line, truncated.

Why?

 [Image of list view issue](https://www.dropbox.com/s/ctkig5v3lhbr7lw/Screenshot_20201118-104203_Squeezer.jpg?dl=0) 

That image shows TWO entries in a list view. Those two items consume 18 lines of the available screen. As you can imagine it takes a long time to scroll this list to find things.

This problem is less acute for some kinds of music (e.g., pop or rock) but is much more prevalent for classical, opera, and jazz where the titles and artists can be quite extensive).

**Comment by kaaholst** [comment]
Good point, thanks for the feedback. 

I will provide an option to select how much info to display in the next version.

**Comment by kaaholst** [comment]
This is available in Squeezer version 2.2.2, so closing this issue.
