### ISSUE TITLE
Issue: FLAC reproduction - Impossible to convert sequence

### ISSUE THREAD

**Issue by huntethan2** [nikclayton/android-squeezer#668]
After one of the recent updates (not sure which one) FLAC files that were playing fine through Squeezer from my Squeezebox server are no longer being reproduced. I'm getting a "Problema: Imposible convertir secuencia"...guess the original error message in English would be something like "Error/Issue: Impossible to convert sequence". 

As further information: this is not happening with all FLAC files, some of them can be still reproduced fine. I've tested the ones raising the errors with other applications other than Squeezer and they can be still played without issues.

If it helps, here are the details of one of those FLAC files failing to be reproduced: 
Bitrate: 2316k
Sample Rate: 96.0 kHz
24Bits
Encoded with: reference libFLAC 1.3.0 20130526

Let me know if I can provide further information.

Thanks!

**Comment by kaaholst** [comment]
Thanks for taking the time to report this.

Immediately this looks like a LMS (Squeezebox server) issue. Audio files are not played through Squeezer. Squeezer acts as a remote control to LMS, communicating only with LMS. LMS communicates (including streaming) with the Squeezebox Player(s).

I suggest you try to rescan you music library for LMS. This can be done e.g. from Squeezer. From the Home screen select Settings / Advanced / Rescan Music Library, and select Rescan Type: "Clear library and rescan everything".

Hope this helps.

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/669](https://github.com/kaaholst/android-squeezer/issues/669)

Please use that for future comments.
