### ISSUE TITLE
Feature Request: Synchronized Volume Control

### ISSUE THREAD

**Issue by o-Axle-o** [nikclayton/android-squeezer#669]
I noticed there's no control to changed the volume of all synchronized players.  Music will play synchronized but the volume is still individually controlled without a "global" control slider.  Adding a slider either above the grouping or below would be very valuable.  Thank you for your consideration.

**Comment by H34dl3ss** [comment]
Pretty much the same as #652 
The same workaround may apply for the time being.

**Comment by kaaholst** [comment]
This will be tracked in #652 so closing this
