### ISSUE TITLE
Request URL Schema

### ISSUE THREAD

**Issue by RoabEnter** [nikclayton/android-squeezer#670]
I would like te request an URL Schema to launce the Squeezer app from an ohter app on my android phone.

It would be great if the app could also be opened in a certain room.

Example:

Open the app in the home screen

squeezer: // squeezectrl /

Optional: Opens the app with the specified player

squeezer: // squeezectrl /? sboxplayer = <MAC>

Thanks in advance!

**Comment by jovrstra** [comment]
I came here with the same question... I would like to launch Squeezer from a home automation app (Loxone) and it requires an URL. So far I haven't even managed to start Squeezer at all, but a scheme to go to a specific player or so would be fantastic!

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/671](https://github.com/kaaholst/android-squeezer/issues/671)

Please use that for future comments.
