### ISSUE TITLE
Display PDF

### ISSUE THREAD

**Issue by schmitzlucien** [nikclayton/android-squeezer#672]
[Hi](url
![Screenshot_20201226-180548_Squeezer](https://user-images.githubusercontent.com/31885026/103156220-c62e5300-47a6-11eb-9f04-0786c483ba34.jpg)
![Screenshot_20201226-180555_Squeezer](https://user-images.githubusercontent.com/31885026/103156221-c6c6e980-47a6-11eb-807b-07d8527e8873.jpg)
![Screenshot_20201226-180605_Squeezer](https://user-images.githubusercontent.com/31885026/103156223-c75f8000-47a6-11eb-9195-80f516475e6c.jpg)

) Nick, Thank you for the great work on Squeezer. I have started to scan my CD booklets and I would like to raise the following feature request. When I click on 'Text files from music folders' the booklet PDF is listed as one of the available files (see 1). But when I click on 'booklet.pdf' (see 2) the error message (see 3) is displayed. I know this is not a 'text file', but nevertheless Android is able to display PDF content. Thanks for considering my feature request and again congratulations for this great app! Regards, Lucien[](url)

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/673](https://github.com/kaaholst/android-squeezer/issues/673)

Please use that for future comments.
