### ISSUE TITLE
Feature request: Trackstat ratings on Now Playing screen

### ISSUE THREAD

**Issue by papatistos** [nikclayton/android-squeezer#673]
It would be great to have Trackstat ratings accessible on the Now Playing screen. More specifically, I would imagine five stars being displayed, some of which (based on the track's rating) would be filled while the others remain empty. The rating can then by changed by long-tapping on the stars.

Also, it would be nice if the ratings could be displayed in the playlist.

Thanks for maintain this project. Great to see so many people still sticking to squeezebox system after all these years!

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/674](https://github.com/kaaholst/android-squeezer/issues/674)

Please use that for future comments.
