### ISSUE TITLE
When playing random tracks with the tags of the tracks are not shown in the app

### ISSUE THREAD

**Issue by viertelb** [nikclayton/android-squeezer#675]
I can chose to play a certain genre of music from the app or from the browser (play by title) from the "random play" menu and the mp3 tags of the tracks will be shown correctly in the Logitech Media Server browser. But they are not shown in the app when playing. 

Squeezer 2.2.2 (and 2.2.1)
Logitech Media Server Version: 7.9.2 

Thanks for the great app! I would be happy to use my small java knowledge to help out. :)

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/676](https://github.com/kaaholst/android-squeezer/issues/676)

Please use that for future comments.
