### ISSUE TITLE
Artist and album "unknown" in some interfaces

### ISSUE THREAD

**Issue by dubbub801** [nikclayton/android-squeezer#677]
Artist and album information is listed in playlist, but this information is "unknown" on the now playing screen and status bar. 

![Screenshot_20210216-080828](https://user-images.githubusercontent.com/79155888/108086205-5c5a5900-7033-11eb-929b-040361b35baa.png)

![Screenshot_20210216-080804](https://user-images.githubusercontent.com/79155888/108086207-5d8b8600-7033-11eb-8c94-8abd1d3ea437.png)

Version 2.2.2
Android 9
SqueezeCenter 7.3.4

**Comment by kaaholst** [comment]
I have not heard of this issue before. My guess is this version of LMS (SqueezeCenter 7.3.4) does not sent album or artist information with the "status" command in menu mode, which Squeezer uses for the Now Playing screen.

If possible try to upgrade your LMS.

Thanks for taking the time to report this.

**Comment by dubbub801** [comment]
Thanks. 

I'm deliberately using the final version released by Slim Devices before the change to Logitech, due to library issues (unrelated to Squeezer) I've had with the more recent versions. This is the lesser problem so I'll live with it.
