### ISSUE TITLE
please retrofit labeling from Spotify.

### ISSUE THREAD

**Issue by anjoku** [nikclayton/android-squeezer#680]
please retrofit labeling from Spotify.

What I absolutely miss is the lack of labeling of Spotify (possibly also Tidal) titles when you mix the albums from local albums and online albums. In the web interface of the LMS server, the Spotify albums are marked with a small Spotify logo so that you can tell them apart.

Best regards

Andre

**Comment by kaaholst** [comment]
We have moved to another github repository, where issues can be reported and followed. There is an issue tracking this problem [https://github.com/kaaholst/android-squeezer/issues/679](https://github.com/kaaholst/android-squeezer/issues/679), so closing this.

Thank you!
