### ISSUE TITLE
Icon for TVH plugin not showing

### ISSUE THREAD

**Issue by andrew-codechimp** [nikclayton/android-squeezer#681]
I'm the creator of the TVH plugin https://github.com/codechimp-org/lms-tvh and I've had a user say the icon isn't showing up in Squeezer.
I'm not doing anything odd with the icon and have followed many other plugin patterns, with the most recent modification being adding the optional material icon for Material Skin (see https://github.com/CDrummond/lms-material/wiki/Plugin-icon-mapping)

I'm not an Android user so haven't validated this myself and not sure if you are holding custom icons for plugins yourself.
Happy to work with you if there's something specific one or other app needs to fix.

**Comment by kaaholst** [comment]
Hi and thanks for the feedback,

Let me initially say, that Squeezer does not do anything special for any plugin. We connect to the server and get a list of players. The user selects a player, and we query the server for a menu for that player. Squeezer then displays those menu items, without really knowing what they are.

I wasn't totally sure what this error exactly was, so I followed the fine instructions on enabling the plugin, and in my setup the icon is indeed not showing, just as your user says.

I've included some screenshots to illustrate the issue, and the data the server sends (json). 

Note "icon-id" field in the TVH entry:
`"icon-id": "plugins/TVH/icon_svg.png"`
 which results in this error from the Squeezer log:
2021-03-17 20:59:17.638 6035-6112/uk.org.ngo.squeezer E/ImageFetcher: Error in downloadUrlToStream - http://10.0.02.2:9000/plugins/TVH/icon_svg.pngjava.io.FileNotFoundException: http://10.0.02.2:9000/plugins/TVH/icon_svg.png

I don't know the internals of the server but if I e.g. list internet radio stations I get for example this:
`"icon-id": "plugins/BBCiPlayer/html/images/bbciplayer.png"`
which displays fine.

You can try these URL's in a browser by prepending the address for the servers web-interface.

The protocol Squeezer uses is defined here:
https://wiki.slimdevices.com/index.php/SqueezeCenterSqueezePlayInterface.html
 
Hope this helps. Please let me know, if you any more info, or if you think there something Squeezer should do to display the icon.

![device-2021-03-17-202111](https://user-images.githubusercontent.com/428304/111530683-e1847b00-8763-11eb-88aa-47d20d62c530.png)
![device-2021-03-17-202250](https://user-images.githubusercontent.com/428304/111530680-e0534e00-8763-11eb-80b4-057c473d5d46.png)

```{
  "ext": {
    "priority": ""
  },
  "data": {
    "offset": 0,
    "count": 4,
    "window": {
      "windowStyle": "home_menu"
    },
    "item_loop": [
      {
        "addAction": "go",
        "icon": "https://www.mysqueezebox.com/static/images/icons/bbc.png",
        "text": "BBC",
        "type": "link",
        "actions": {
          "go": {
            "cmd": [
              "myapps",
              "items"
            ],
            "params": {
              "item_id": "d001af79.0",
              "menu": "myapps"
            }
          }
        }
      },
      {
        "addAction": "go",
        "icon": "https://www.mysqueezebox.com/static/images/icons/deezer.png",
        "text": "Deezer",
        "type": "link",
        "actions": {
          "go": {
            "cmd": [
              "myapps",
              "items"
            ],
            "params": {
              "item_id": "d001af79.1",
              "menu": "myapps"
            }
          }
        }
      },
      {
        "addAction": "go",
        "icon-id": "plugins/TVH/icon_svg.png",
        "text": "TVH",
        "type": "redirect",
        "actions": {
          "go": {
            "cmd": [
              "TVH",
              "items"
            ],
            "params": {
              "menu": "TVH"
            }
          }
        }
      },
      {
        "addAction": "go",
        "icon": "https://www.mysqueezebox.com/static/images/icons/tuneinradio.png",
        "text": "TuneIn Radio",
        "type": "link",
        "actions": {
          "go": {
            "cmd": [
              "myapps",
              "items"
            ],
            "params": {
              "item_id": "d001af79.3",
              "menu": "myapps"
            }
          }
        }
      }
    ],
    "title": "My Apps",
    "base": {
      "actions": {
        "add": {
          "itemsParams": "params",
          "cmd": [
            "myapps",
            "playlist",
            "add"
          ],
          "params": {
            "menu": "myapps"
          },
          "player": 0
        },
        "play": {
          "itemsParams": "params",
          "cmd": [
            "myapps",
            "playlist",
            "play"
          ],
          "nextWindow": "nowPlaying",
          "params": {
            "menu": "myapps"
          },
          "player": 0
        },
        "more": {
          "itemsParams": "params",
          "window": {
            "isContextMenu": 1
          },
          "cmd": [
            "myapps",
            "items"
          ],
          "params": {
            "menu": "myapps"
          },
          "player": 0
        },
        "go": {
          "itemsParams": "params",
          "cmd": [
            "myapps",
            "items"
          ],
          "params": {
            "menu": "myapps"
          }
        },
        "add-hold": {
          "itemsParams": "params",
          "cmd": [
            "myapps",
            "playlist",
            "insert"
          ],
          "params": {
            "menu": "myapps"
          },
          "player": 0
        },
        "playControl": {
          "itemsParams": "playControlParams",
          "window": {
            "isContextMenu": 1
          },
          "cmd": [
            "myapps",
            "items"
          ],
          "params": {
            "useContextMenu": "1",
            "_index": "0",
            "_quantity": "50",
            "menu": "myapps"
          },
          "player": 0
        }
      }
    }
  },
  "channel": "/23937e9c/slim/request/2",
  "id": "33"
}`

**Comment by andrew-codechimp** [comment]
Thanks for the very detailed analysis, it's pointed me in the right direction and it seems there were two ways to reference plugin icons.
BBC iPlayer and others are using a newer method of placing them in the HTML folder, typically the pattern I followed didn't.

Version 1.3.30 which I've just released has moved to this method and still works with Squeeze webui and should also work with Squeezer since I can now successfully get the icon from MYSERVER/plugins/TVH/html/images/icon_svg.png

I'd be grateful if you could test this with Squeezer once you update the plugin to confirm, I'll also let the user know over in the discussion I'm having with him.

**Comment by kaaholst** [comment]
Confirmed :+1: (the red triangle is just because I run in debug mode, and signals that the image was not found in cache, i.e. downloaded from the server).
![device-2021-03-18-144453](https://user-images.githubusercontent.com/428304/111661764-9b84f100-880f-11eb-8948-7e1ee40fb3d7.png)

**Comment by andrew-codechimp** [comment]
Thanks for the confirmation!

Sorry I had to raise this issue with you to understand how icons work in plugins but it's been very educational.
