### ISSUE TITLE
Failed setting up new Alarm Clock/ Possible Bug

### ISSUE THREAD

**Issue by Legitwarrior** [nikclayton/android-squeezer#683]
Hi there,
thanks for the great app.
Since last update on android 2.2.4, when I add a new alarm to Squeezebox Touch or Radio, I can't enter the time correctly. For example, when I enter 9:00 it sets a time of 00:09. So it seems that I can't add the correct hour. I tried it on two different android devices and two squeezeboxes.

**Comment by kaaholst** [comment]
Closing this issue [https://github.com/kaaholst/android-squeezer/issues/694](https://github.com/kaaholst/android-squeezer/issues/694) is the proper place to report issues.

We have recently switched to that repository, sorry for any confusion, this has entailed.
