### ISSUE TITLE
Mute tickbox doesn't work

### ISSUE THREAD

**Issue by elslasko** [nikclayton/android-squeezer#685]
Running Spotty via Chromecast bridge plugin. When I use the Mute tickbox under Change Volume, the actual volume from my speakers goes up to MAX, but the level on the app stays the same. I accidentally woke up my family (and neighbours?)

**Comment by kaaholst** [comment]
There was a bug in LMS which prevented mute to work correctly with Chromecast bridge plugin devices. This bug has been fixed in LMS 8.1.2.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few months.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still experience this.

Thank you!
