### ISSUE TITLE
UI Improvements ( Album View / Background Player )

### ISSUE THREAD

**Issue by annomatik** [nikclayton/android-squeezer#686]
Hi! I have two feature requests for UI improvements. In BlackPlayer, there is a very nice album view which uses the display space of my mobile phone nicely and looks good, I've attached a picture. Would it be possible to have something similar in Squeezer two?

Also, BlackPlayer has "background player controls", for the lack of a better description. That is, regardless, in which app I am, I can just drop down from the top of my phone the player controls, skip to the next / previous track there, play/pause the current track, see, how many tracks there are in my current playlist, together with track name, artist name and album art.

Both of these features would be a nice improvement to Squeezer. Thank you!

![blackplayer_album_view](https://user-images.githubusercontent.com/28311452/128571163-a838420b-0ee3-4053-a09d-f10e231f5a76.jpg)
![blackplayer_background_player](https://user-images.githubusercontent.com/28311452/128571170-e0770cd5-e24e-4e2a-8c89-dd806ca23146.jpg)

**Comment by kaaholst** [comment]
Closing this it is tracked in https://github.com/kaaholst/android-squeezer
