### ISSUE TITLE
Not possible to change LMS server?

### ISSUE THREAD

**Issue by NoBagels** [nikclayton/android-squeezer#690]
I have multiple LMS running on my LAN, but have not found any way to chose between them using Squeezer?

**Comment by kaaholst** [comment]
From the 3-dot menu in the top right corner, select disconnect.
Your servers should appear in the drop down list. If not there is an option to enter the IP address of the server manually.

Hope this helps

**Comment by NoBagels** [comment]
Ah, thanks, that helps a lot. A bit more hidden than what I'm used to (searched for something akin to "Change server" but I guess this solves my issue and this topic can be closed. Cheers!
