### ISSUE TITLE
Old vs new group volume

### ISSUE THREAD

**Issue by Phoenixxx3** [nikclayton/android-squeezer#691]
I miss the old volume control, where I can adjust every player individually with the volume buttons. I have a multi-room system with heterogenious players (different max volumes). I always end up at max volume, where in one room the volume is too low and in other room way too high. I am struggeling with this problem with both settings (non-synchronized or synchronized volume).

**Comment by kaaholst** [comment]
I see your point. 

Currently Squeezer will adjust the volume of all synced players, keeping the current volume offsets of the player's volume. 
Unless "Sync player's volume" is selected, in which case LMS will make sure the volume level is the same for the synced players.

I can make a selection in the volume panel where you can choose between this new behaviour, an the old volume control where the volume panel and the volume up/down buttons control only the selected player.

![billede](https://user-images.githubusercontent.com/428304/151061421-bfd0a331-4854-46d1-a35f-c896f6452e9f.png)

**Comment by Phoenixxx3** [comment]
That would be awesome! Thank you!

BTW did i post this in the wrong repo/issue tracker? Should it be there https://github.com/kaaholst/android-squeezer ?

**Comment by kaaholst** [comment]
This is available from version 2.2.8, which is available in Google Play.

Yes you are correct, please use https://github.com/kaaholst/android-squeezer for future issues.
