### ISSUE TITLE
Playlist is not showing the playing song

### ISSUE THREAD

**Issue by EF1973** [nikclayton/android-squeezer#692]
![Screenshot_2022-02-12-17-24-10-06_8e229f184a48671c275153303ae6d3bb](https://user-images.githubusercontent.com/99551418/153719644-23abf245-c849-42cc-adfc-3157f78ca95a.jpg)

Hi, I am using the squeezer for some years now with much pleasure. However since one of the last updates when i am playing a song from the playlist the song on the bottom of the menu is not the same as the one market in the playlist. See enclosed picture. I hope you can help me with thuis issue. I already removed the app and installed it again, but this did not help.

**Comment by kaaholst** [comment]
This should be fixed in version 2.3.5, so closing this. If it doesn't work, feel free to reopen.
