### ISSUE TITLE
squeezer has no single tap 'album play' with new Deezer local plugin

### ISSUE THREAD

**Issue by anotherstuart** [nikclayton/android-squeezer#698]
Hi

As you may know there has been a new Deezer plugin written due to the ending of mysqueezebox. The new plugin is here https://github.com/philippe44/lms-deezer

I am finding that I can play albums as a whole (not track by track) from any interface (e.g. web lms, jivelite, etc) but not from Squeezer.

When the album is on the screen (in a list, with three dots to the right) the only option I get is 'add to favourites' (or remove from favourites if it is already ...)

If i go into the album the tracks appear and I can play the tracks - it is just the 'playing the whole album with one tap from the three dots' that doesn't work.

Of course, I have no way of knowing if this is a Squeezer issue or a lms-Deezer issue, but hope you don't mind me trying here first.

Thanks for any info

**Comment by kaaholst** [comment]
No, I didn't know there was a new plugin for Deezer available, but I'm happy to hear that. Thanks for the feedback!

I will investigate if this is a Squeezer issue, and report back.

In the meantime, I kindly ask you to post this issue on https://github.com/kaaholst/android-squeezer/issues instead, as Squeezer has moved there. Sorry for the inconvenience.
