### ISSUE TITLE
Album/Artist/Song listings have no alphabet short cuts.

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#82]
```
This, combined with the fact that names aren't loaded until scrolling stops, makes it
much more difficult to browse.
Nice to have, if it's lightweight and easy to implement.
Thanks.
```

Original issue reported on code.google.com by `drdocmatt` on 2014-02-15 11:56:47

**Comment by kaaholst** [comment]
The issue tracker has moved to a the new location: [https://github.com/kaaholst/android-squeezer/issues/83](https://github.com/kaaholst/android-squeezer/issues/83)

Please use that for future comments.
