### ISSUE TITLE
Support alarms

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#86]
```
The server supports alarms (see "<playerid> alarm" in the docs).  Squeezer should allow
the user to manipulate alarms.

Requested by mwburfeind@gmail.com
```

Original issue reported on code.google.com by `nik@ngo.org.uk` on 2014-04-05 12:14:06

**Comment by rmac321** [comment]
+1
Wow.  Just created a git-hub login so I could make this suggestion.  Would be very cool if one could turn on/off all alarms, turn on/off individual alarms, view/adjust alarm settings and create alarms from android devices.

**Comment by nikclayton** [comment]
Closing this as the newly released 1.4.0 has alarm clock support.

**Comment by rmac321** [comment]
Nik,
Haven't had a chance to test extensively, but seems to work fine on my motoG with KitKat 4.4.4.  Doesn't show up on my Nexus 7 (2012) with Lollipop 5.1.1 though.
Much easier to get to than on Orange Squeeze.  More functional as well.  Thanks! Ross

--------------------------------------
Ross McNeil
remcneil(AT)sbcglobal(DOT)net

**Comment by nikclayton** [comment]
Are both devices connected to the same server?

When Squeezer starts it sends a query to the server to learn what features it supports (which includes whether or not the server supports alarms). If these are different servers then that might be it.

If it's the same server... then hmm...
