### ISSUE TITLE
Support managing equalizer settings

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#87]
```
Players have some equalizer settings ("mixer {bass,treble,pitch}").  Expose these in
the UI and allow users to adjust them.

Requested by mwburfeind@gmail.com
```

Original issue reported on code.google.com by `nik@ngo.org.uk` on 2014-04-05 12:20:28

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

This may be supported via the CometD protocol. If not please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
