### ISSUE TITLE
blank album art

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#93]
```
What steps will reproduce the problem?
1.  No album art is visible.

What is the expected output? What do you see instead?

Instead of album covers I see black squares.  Note that I don't see the default icon
that shows when there is no album art.

What version of the product are you using? On what operating system?

Squeezer 1.0.1 on a Nexus 7 with android 4.4.3


Please provide any additional information below.

I have the old squeezebox that doesn't show album art, so I never had a reason to get
album covers until I started using Squeezer.  I recently downloaded album covers, and
they show up in the squeezebox server web interface, but not in Squeezer.

Squeezer is a great app by the way!

```

Original issue reported on code.google.com by `npoysti` on 2014-06-10 22:45:43

**Comment by chau-intl** [comment]
@nikclayton, I was wondering if this very old issue was related to the cover on a specific track from LMS or related to the cover for an entire folder/album?

When navigating to "My Music"/"Music Folder"/Movie, I see covers on individual tracks (where the cover is embedded in the track) but NOT on folders containing albums (which each has their own cover.jpg).

Is it possible to also get a cover for folders using Squeezer/LMS or is it not implemented in LMS? I'm just not sure if it is possible or if it is an issue somewhere in my setup.
