### ISSUE TITLE
SD card

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#94]
```
Would it be possible to add the choice to transfer the android-squeezer and the collected
art work to SD card? 
```

Original issue reported on code.google.com by `Davor281` on 2014-07-05 20:05:18

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
