### ISSUE TITLE
Support transcoding for downloads

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#96]
```
Support transcoding while downloading files. Add settings to which format should be
transcoded and in which quality. Squeezebox server supports transcoding of files during
download.
```

Original issue reported on code.google.com by `pascal.berger` on 2014-08-02 09:52:29

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
